/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package caja.interfazCaja;

import hacerPedido.procesos.cobros.DescuentoInterfaz;
import java.math.BigDecimal;
import java.math.RoundingMode;

/**
 *
 * @author aleja
 */
public class InterfazCajas extends javax.swing.JFrame {

    private String cantidadPropuesta = "0.00";
    private boolean billetesIntroducidos = false;
    private static BigDecimal importeTotalPagar;

    /**
     * Creates new form InterfazCajas
     *
     * @param importeTotal es el importe total que hay que igualar o superar
     * para pagar
     */
    public InterfazCajas(BigDecimal importeTotal) {
        initComponents();
        actualizarPantalla();

        importeTotalPagar = importeTotal;
        textoCantidadTotalPagar.setText(String.valueOf(importeTotal));

        // Hacemos desaparecer la devolucion
        textoDevolucion.setText("");
        textoDevolucionCantidad.setText("");
    }

    /**
     * Este metodo actualiza la pantalla con los datos introducidos
     */
    private void actualizarPantalla() {
        textoCantidadPagado.setText(cantidadPropuesta);
        textoCantidadTotalPagar.setText(String.valueOf(importeTotalPagar));
    }

    /**
     * Este metodo permite anadir un numero, para ello se introduce el numero y
     * lo devuelve
     *
     * @param numero es el numero que se va a anadir a la cadena
     */
    private void anadirNumero(int numero) {

        //En caso de se hayan introducidos previamente billetes se reinicia la cantidad
        if (billetesIntroducidos) {
            cantidadPropuesta = "0.00";
            billetesIntroducidos = false;
        }

        // Eliminar la coma y formar el número completo como una cadena
        String sinComa = cantidadPropuesta.replace(".", "");
        // Desplazar los caracteres hacia la izquierda y agregar el nuevo dígito
        sinComa = sinComa.substring(1) + numero;

        // Insertar nuevamente la coma para que sea un número con dos decimales
        StringBuilder sb = new StringBuilder(sinComa);
        sb.insert(sb.length() - 2, '.');

        // Actualizamos la cantidad propuesta y actualizamos la pantalla
        cantidadPropuesta = sb.toString();
        actualizarPantalla();
    }

    private void billetes(int billete) {
        if (!billetesIntroducidos) {
            cantidadPropuesta = "0.00";
        }
        BigDecimal can = BigDecimal.ZERO;
        if (cantidadPropuesta.equalsIgnoreCase("")) {
            cantidadPropuesta = "0.00";
        } else {
            can = new BigDecimal(cantidadPropuesta);
        }
        can = can.add(new BigDecimal(billete));
        cantidadPropuesta = can.toString();
        actualizarPantalla();
        billetesIntroducidos = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        botonCobrar = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonPromo = new javax.swing.JButton();
        botonBillete10 = new javax.swing.JButton();
        botonBillete5 = new javax.swing.JButton();
        botonBillete50 = new javax.swing.JButton();
        botonBillete20 = new javax.swing.JButton();
        botonDesc = new javax.swing.JButton();
        textoTotalPagar = new javax.swing.JLabel();
        textoCantidadTotalPagar = new javax.swing.JLabel();
        textoPagado = new javax.swing.JLabel();
        textoCantidadPagado = new javax.swing.JLabel();
        textoBilletes = new javax.swing.JLabel();
        importeExacto = new javax.swing.JButton();
        textoDevolucion = new javax.swing.JLabel();
        textoDevolucionCantidad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu cobrar");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        boton1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        boton1.setText("1");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });

        boton2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        boton2.setText("2");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });

        boton3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        boton3.setText("3");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });

        boton5.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        boton5.setText("5");
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });

        boton6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        boton6.setText("6");
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });

        boton4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        boton4.setText("4");
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });

        boton8.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        boton8.setText("8");
        boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton8ActionPerformed(evt);
            }
        });

        boton9.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        boton9.setText("9");
        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });

        boton7.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        boton7.setText("7");
        boton7.setToolTipText("");
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });

        boton0.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        boton0.setText("0");
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });

        botonCobrar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        botonCobrar.setText("Cobrar");
        botonCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCobrarActionPerformed(evt);
            }
        });

        botonBorrar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        botonBorrar.setText("Borrar");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        botonPromo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        botonPromo.setText("PROMO");

        botonBillete10.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        botonBillete10.setText("10");
        botonBillete10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBillete10ActionPerformed(evt);
            }
        });

        botonBillete5.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        botonBillete5.setText("5");
        botonBillete5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBillete5ActionPerformed(evt);
            }
        });

        botonBillete50.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        botonBillete50.setText("50");
        botonBillete50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBillete50ActionPerformed(evt);
            }
        });

        botonBillete20.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        botonBillete20.setText("20");
        botonBillete20.setToolTipText("");
        botonBillete20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBillete20ActionPerformed(evt);
            }
        });

        botonDesc.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        botonDesc.setText("DESC");
        botonDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDescActionPerformed(evt);
            }
        });

        textoTotalPagar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoTotalPagar.setText("TOTAL PAGAR:");

        textoCantidadTotalPagar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoCantidadTotalPagar.setText("Cantidad1");

        textoPagado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoPagado.setText("PAGADO:");

        textoCantidadPagado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoCantidadPagado.setText("Cantidad2");

        textoBilletes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoBilletes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoBilletes.setText("SELECCIONA EL BILLETE");

        importeExacto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        importeExacto.setText("<html>Importe<br>Exacto</html> ");
        importeExacto.setToolTipText("");
        importeExacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importeExactoActionPerformed(evt);
            }
        });

        textoDevolucion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoDevolucion.setText("DEVOLUCION: ");

        textoDevolucionCantidad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoDevolucionCantidad.setForeground(new java.awt.Color(255, 0, 0));
        textoDevolucionCantidad.setText("Cantidad1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoPagado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoCantidadPagado))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(boton0, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(botonCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(boton7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(boton8, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(boton9, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(boton5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(boton6, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(textoTotalPagar)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(textoCantidadTotalPagar))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(textoDevolucion)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(textoDevolucionCantidad)))
                                    .addGap(46, 46, 46)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(botonBillete20, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(botonBillete50, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(botonBillete5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(botonBillete10, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(textoBilletes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(importeExacto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoCantidadTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPagado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoCantidadPagado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoDevolucionCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botonDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textoBilletes)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton0, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonBorrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonBillete5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonBillete10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonBillete20, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonBillete50, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(importeExacto, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDescActionPerformed
        DescuentoInterfaz des = new DescuentoInterfaz();
        des.setVisible(true);
    }//GEN-LAST:event_botonDescActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        anadirNumero(1);
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        anadirNumero(2);
    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        anadirNumero(3);
    }//GEN-LAST:event_boton3ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
        anadirNumero(4);
    }//GEN-LAST:event_boton4ActionPerformed

    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed
        anadirNumero(5);
    }//GEN-LAST:event_boton5ActionPerformed

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
        anadirNumero(6);
    }//GEN-LAST:event_boton6ActionPerformed

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
        anadirNumero(7);
    }//GEN-LAST:event_boton7ActionPerformed

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed
        anadirNumero(8);
    }//GEN-LAST:event_boton8ActionPerformed

    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed
        anadirNumero(9);
    }//GEN-LAST:event_boton9ActionPerformed

    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed
        if (!cantidadPropuesta.equalsIgnoreCase("0.00")) {
            anadirNumero(0);
        }
    }//GEN-LAST:event_boton0ActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        cantidadPropuesta = "0.00";
        actualizarPantalla();
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonBillete5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBillete5ActionPerformed
        billetes(5);
    }//GEN-LAST:event_botonBillete5ActionPerformed

    private void botonBillete10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBillete10ActionPerformed
        billetes(10);
    }//GEN-LAST:event_botonBillete10ActionPerformed

    private void botonBillete20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBillete20ActionPerformed
        billetes(20);
    }//GEN-LAST:event_botonBillete20ActionPerformed

    private void botonBillete50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBillete50ActionPerformed
        billetes(50);
    }//GEN-LAST:event_botonBillete50ActionPerformed

    private void importeExactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importeExactoActionPerformed
        cantidadPropuesta = String.valueOf(importeTotalPagar);
        actualizarPantalla();
        botonCobrarActionPerformed(null);
    }//GEN-LAST:event_importeExactoActionPerformed

    private void botonCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCobrarActionPerformed
        // Calculamos el importe de devolucion
        BigDecimal cantidadPropuestaBD = new BigDecimal(cantidadPropuesta); // Convertir cantidadPropuesta a BigDecimal

        // Compara cantidadPropuesta con importeTotalPagar
        if (cantidadPropuestaBD.compareTo(importeTotalPagar) < 0) {
            // Si cantidadPropuesta es menor que importeTotalPagar
            importeTotalPagar = importeTotalPagar.subtract(cantidadPropuestaBD); // Resta la cantidad propuesta
            cantidadPropuesta = "0.00"; // Reinicia cantidadPropuesta
        } else {
            // Hacemos aparecer la devolución
            BigDecimal devolucion = cantidadPropuestaBD.subtract(importeTotalPagar); // Calcula la devolución
            importeTotalPagar = new BigDecimal(0);
            textoDevolucion.setText("DEVOLVER:");
            textoDevolucionCantidad.setText(devolucion.setScale(2, RoundingMode.HALF_UP).toString()); // Muestra la devolución con 2 decimales
        }
        //Actualizamos la pantalla y ponemos el precio a 0
        actualizarPantalla();


    }//GEN-LAST:event_botonCobrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InterfazCajas(new BigDecimal("9.00")).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JButton botonBillete10;
    private javax.swing.JButton botonBillete20;
    private javax.swing.JButton botonBillete5;
    private javax.swing.JButton botonBillete50;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonCobrar;
    private javax.swing.JButton botonDesc;
    private javax.swing.JButton botonPromo;
    private javax.swing.JButton importeExacto;
    private javax.swing.JLabel textoBilletes;
    private javax.swing.JLabel textoCantidadPagado;
    private javax.swing.JLabel textoCantidadTotalPagar;
    private javax.swing.JLabel textoDevolucion;
    private javax.swing.JLabel textoDevolucionCantidad;
    private javax.swing.JLabel textoPagado;
    private javax.swing.JLabel textoTotalPagar;
    // End of variables declaration//GEN-END:variables
}
