package caja.interfazCaja;

import caja.modelo.Caja;
import javax.swing.JLabel;

/**
 * Interfaz grafica que representa la informacion basica de la caja
 *
 * @author Alejandro Perellón López
 */
public class PanelCaja extends javax.swing.JPanel {

    private Caja caja;

    /**
     * Creates new form PanelCaja
     */
    public PanelCaja(Caja caja) {
        initComponents();
        this.caja = caja;
    }

    public void iniciarPanelCaja() {
        ejecutarHora();

        DatosEmpleado.setText(caja.getEmpleado().getNombre() + "(" + caja.getEmpleado().getIdRestauranteEmpleado() + ")");
        establecerEstadoActividadCaja();
        establecerPuestoSesionCaja();
    }

    /**
     * Metodo que establece el numero de caja y la sesion de la caja que esta
     * siendo actualmente ocupada
     */
    private void establecerPuestoSesionCaja() {
        PuestoSesion.setText("Puesto " + caja.getNumeroCaja() + " | Sesion " + caja.getNumeroSesion());
    }

    /**
     * Metodo que establece el estado de la caja, si la caja no contiene una
     * fecha de cierre se considera como desactivada, en caso de contenerla se
     * considera activa
     */
    private void establecerEstadoActividadCaja() {
        if (caja.getMomentoCierre() != null) {
            estadoCaja.setText("Desactivada");
            estadoCaja.setBackground(new java.awt.Color(245, 183, 177));
        } else {
            estadoCaja.setText("Activa");
            estadoCaja.setBackground(new java.awt.Color(218, 247, 166));
        }
    }

    /**
     * Metodo que ejecuta el hilo del reloj con la hora actual
     */
    public void ejecutarHora() {
        new Reloj(fechaHora).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fechaHora = new javax.swing.JLabel();
        DatosEmpleado = new javax.swing.JLabel();
        PuestoSesion = new javax.swing.JLabel();
        estadoCaja = new javax.swing.JLabel();
        TiempoPedido = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        fechaHora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fechaHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechaHora.setText("00/00/2000   00:00:00");

        DatosEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DatosEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DatosEmpleado.setText("No hay usuario activo");

        PuestoSesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PuestoSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PuestoSesion.setText("Puesto X | Sesion X");

        estadoCaja.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        estadoCaja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estadoCaja.setText("Cerrada");

        TiempoPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TiempoPedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TiempoPedido.setText("00:00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TiempoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DatosEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PuestoSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(estadoCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaHora)
                    .addComponent(DatosEmpleado)
                    .addComponent(PuestoSesion)
                    .addComponent(estadoCaja)
                    .addComponent(TiempoPedido))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public Caja getCaja() {
        return caja;
    }

    public JLabel getDatosEmpleado() {
        return DatosEmpleado;
    }

    public JLabel getPuestoSesion() {
        return PuestoSesion;
    }

    public JLabel getEstadoCaja() {
        return estadoCaja;
    }

    public JLabel getFechaHora() {
        return fechaHora;
    }

    public JLabel getTiempoPedido() {
        return TiempoPedido;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DatosEmpleado;
    private javax.swing.JLabel PuestoSesion;
    private javax.swing.JLabel TiempoPedido;
    private javax.swing.JLabel estadoCaja;
    private javax.swing.JLabel fechaHora;
    // End of variables declaration//GEN-END:variables
}
