/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package caja.interfazCaja;

import caja.modelo.Caja;
import usuarios.Empleados;
import usuarios.GestionEmpleados;

/**
 *
 * @author aleja
 */
public class PanelCaja extends javax.swing.JPanel {

    /**
     * Creates new form PanelCaja
     */
    public PanelCaja(Caja caja) {
        initComponents();
        ejecutarHora();
        
        DatosEmpleado.setText(caja.getEmpleado().getNombre() + "(" + caja.getEmpleado().getId() + ")");
        establecerIconoActividadCaja(caja);
        establecerPuestoSesionCaja(caja);
    }

    private void establecerPuestoSesionCaja(Caja caja) {
        PuestoSesion.setText("Puesto " + caja.getNumeroCaja() + " | Sesion " + caja.getNumeroSesion());
    }

    private void establecerIconoActividadCaja(Caja caja) {
        if (caja.getEstadoCaja().equalsIgnoreCase("Cerrada")) {
            estadoCaja.setText("Desactivada");
            estadoCaja.setBackground(new java.awt.Color(245, 183, 177));
        } else if (caja.getEstadoCaja().equalsIgnoreCase("operativa")) {
            estadoCaja.setText("Activa");
            estadoCaja.setBackground(new java.awt.Color(218, 247, 166));
        }
    }

    public void ejecutarHora() {
        new Reloj(fechaHora).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fechaHora = new javax.swing.JLabel();
        DatosEmpleado = new javax.swing.JLabel();
        PuestoSesion = new javax.swing.JLabel();
        estadoCaja = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        fechaHora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fechaHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechaHora.setText("00/00/2000   00:00:00");

        DatosEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DatosEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DatosEmpleado.setText("Alejandro Perellon Lopez");

        PuestoSesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PuestoSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PuestoSesion.setText("Puesto X | Sesion X");

        estadoCaja.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        estadoCaja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estadoCaja.setText("Cerrada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DatosEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PuestoSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(estadoCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaHora)
                    .addComponent(DatosEmpleado)
                    .addComponent(PuestoSesion)
                    .addComponent(estadoCaja))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DatosEmpleado;
    private javax.swing.JLabel PuestoSesion;
    private javax.swing.JLabel estadoCaja;
    private javax.swing.JLabel fechaHora;
    // End of variables declaration//GEN-END:variables
}
