package basesDatos.casillaProductos;

import javax.swing.JLabel;
import productos.modelo.Producto;

/**
 * Metodo que muestra la casilla de un producto junto con la informacion del
 * estado en la base de datos
 *
 * @author Alejandro Perellón López
 */
public class CasillaProducto extends javax.swing.JPanel {

    private boolean mostrarEstado;

    private Producto producto;

    private CasillaProductoMetodos metodos;

    /**
     * Creates new form CasillaProducto
     */
    public CasillaProducto(boolean mostrarEstado, Producto producto) {
        initComponents();
        this.mostrarEstado = mostrarEstado;
        this.producto = producto;
        this.metodos = new CasillaProductoMetodos(this, producto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagenProducto = new javax.swing.JLabel();
        nombreProducto = new javax.swing.JLabel();
        estadoProducto = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        imagenProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficaErrorProducto/imageNotFound64.png"))); // NOI18N

        nombreProducto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nombreProducto.setText("Nombre del producto");

        estadoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficaErrorProducto/imageNotFound64.png"))); // NOI18N
        estadoProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estadoProductoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estadoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombreProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imagenProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estadoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void estadoProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estadoProductoMouseClicked
        metodos.invertirEstadoProducto();
    }//GEN-LAST:event_estadoProductoMouseClicked

    public boolean isMostrarEstado() {
        return mostrarEstado;
    }

    public JLabel getEstadoProducto() {
        return estadoProducto;
    }

    public JLabel getImagenProducto() {
        return imagenProducto;
    }

    public JLabel getNombreProducto() {
        return nombreProducto;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel estadoProducto;
    private javax.swing.JLabel imagenProducto;
    private javax.swing.JLabel nombreProducto;
    // End of variables declaration//GEN-END:variables
}
