package auxiliares.tecladoPantalla;

import auxiliares.inicioAplicacion.ConfiguracionInicial;
import javax.swing.JLabel;

/**
 * Clase de dialogo modal que muestra un teclado para poder solicitar un texto
 *
 * @author Alejandro Perellón López
 */
public class TecladoEnPantalla extends javax.swing.JDialog {

    TecladoEnPantallaMetodos metodos = new TecladoEnPantallaMetodos(this);

    StringBuilder cadena = new StringBuilder();

    /**
     * Creates new form tecladoEnPantalla
     */
    public TecladoEnPantalla() {
        super(ConfiguracionInicial.get().getVentanaPrincipal(), true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        letraq = new javax.swing.JButton();
        letraW = new javax.swing.JButton();
        letraE = new javax.swing.JButton();
        letraR = new javax.swing.JButton();
        letraT = new javax.swing.JButton();
        letraY = new javax.swing.JButton();
        letraU = new javax.swing.JButton();
        letraI = new javax.swing.JButton();
        letraP = new javax.swing.JButton();
        letraO = new javax.swing.JButton();
        letraA = new javax.swing.JButton();
        letraS = new javax.swing.JButton();
        letraD = new javax.swing.JButton();
        letraF = new javax.swing.JButton();
        letraG = new javax.swing.JButton();
        letraH = new javax.swing.JButton();
        letraJ = new javax.swing.JButton();
        letraK = new javax.swing.JButton();
        letraL = new javax.swing.JButton();
        letraÑ = new javax.swing.JButton();
        letraZ = new javax.swing.JButton();
        letraX = new javax.swing.JButton();
        letraC = new javax.swing.JButton();
        letraV = new javax.swing.JButton();
        letraB = new javax.swing.JButton();
        letraN = new javax.swing.JButton();
        letraM = new javax.swing.JButton();
        textoIntroducido = new javax.swing.JLabel();
        botonContinuar = new javax.swing.JButton();
        letraEspacio = new javax.swing.JButton();
        letraBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Teclado en pantalla");
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        letraq.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraq.setText("Q");
        letraq.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraqActionPerformed(evt);
            }
        });

        letraW.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraW.setText("W");
        letraW.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraWActionPerformed(evt);
            }
        });

        letraE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraE.setText("E");
        letraE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraEActionPerformed(evt);
            }
        });

        letraR.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraR.setText("R");
        letraR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraRActionPerformed(evt);
            }
        });

        letraT.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraT.setText("T");
        letraT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraTActionPerformed(evt);
            }
        });

        letraY.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraY.setText("Y");
        letraY.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraYActionPerformed(evt);
            }
        });

        letraU.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraU.setText("U");
        letraU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraUActionPerformed(evt);
            }
        });

        letraI.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraI.setText("I");
        letraI.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraIActionPerformed(evt);
            }
        });

        letraP.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraP.setText("P");
        letraP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraPActionPerformed(evt);
            }
        });

        letraO.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraO.setText("O");
        letraO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraOActionPerformed(evt);
            }
        });

        letraA.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraA.setText("A");
        letraA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraAActionPerformed(evt);
            }
        });

        letraS.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraS.setText("S");
        letraS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraSActionPerformed(evt);
            }
        });

        letraD.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraD.setText("D");
        letraD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraDActionPerformed(evt);
            }
        });

        letraF.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraF.setText("F");
        letraF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraFActionPerformed(evt);
            }
        });

        letraG.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraG.setText("G");
        letraG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraGActionPerformed(evt);
            }
        });

        letraH.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraH.setText("H");
        letraH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraHActionPerformed(evt);
            }
        });

        letraJ.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraJ.setText("J");
        letraJ.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraJActionPerformed(evt);
            }
        });

        letraK.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraK.setText("K");
        letraK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraKActionPerformed(evt);
            }
        });

        letraL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraL.setText("L");
        letraL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraLActionPerformed(evt);
            }
        });

        letraÑ.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraÑ.setText("Ñ");
        letraÑ.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraÑ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraÑActionPerformed(evt);
            }
        });

        letraZ.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraZ.setText("Z");
        letraZ.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraZActionPerformed(evt);
            }
        });

        letraX.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraX.setText("X");
        letraX.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraXActionPerformed(evt);
            }
        });

        letraC.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraC.setText("C");
        letraC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraCActionPerformed(evt);
            }
        });

        letraV.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraV.setText("V");
        letraV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraVActionPerformed(evt);
            }
        });

        letraB.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraB.setText("B");
        letraB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraBActionPerformed(evt);
            }
        });

        letraN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraN.setText("N");
        letraN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraNActionPerformed(evt);
            }
        });

        letraM.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraM.setText("M");
        letraM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraMActionPerformed(evt);
            }
        });

        textoIntroducido.setBackground(new java.awt.Color(255, 255, 255));
        textoIntroducido.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        textoIntroducido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoIntroducido.setText("Introduce un texto");
        textoIntroducido.setToolTipText("Introduce un texto");

        botonContinuar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botonContinuar.setText("Continuar");
        botonContinuar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonContinuarActionPerformed(evt);
            }
        });

        letraEspacio.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraEspacio.setText("Espacio");
        letraEspacio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraEspacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraEspacioActionPerformed(evt);
            }
        });

        letraBorrar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        letraBorrar.setText("Borrar ");
        letraBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letraBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(letraEspacio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letraBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textoIntroducido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(letraq, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(letraW, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(letraE, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(letraR, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(letraT, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(letraY, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(letraU, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(letraI, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(letraO, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(letraP, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(letraZ, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(letraX, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(letraC, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(letraV, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(letraB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(letraN, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(letraM, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botonContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(letraA, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(letraS, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(letraD, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(letraF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(letraG, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(letraH, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(letraJ, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(letraK, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(letraL, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(letraÑ, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(textoIntroducido, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letraq, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraW, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraE, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraR, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraT, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraY, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraU, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraI, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraO, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraP, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letraA, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraS, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraD, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraG, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraH, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraJ, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraK, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraL, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraÑ, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letraZ, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraX, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraC, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraV, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraN, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraM, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letraEspacio, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(letraBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void letraqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraqActionPerformed
       metodos.anadirLetra("q");
    }//GEN-LAST:event_letraqActionPerformed

    private void letraWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraWActionPerformed
       metodos.anadirLetra("w");
    }//GEN-LAST:event_letraWActionPerformed

    private void letraEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraEActionPerformed
        metodos.anadirLetra("e");
    }//GEN-LAST:event_letraEActionPerformed

    private void letraRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraRActionPerformed
        metodos.anadirLetra("r");
    }//GEN-LAST:event_letraRActionPerformed

    private void letraTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraTActionPerformed
       metodos.anadirLetra("t");
    }//GEN-LAST:event_letraTActionPerformed

    private void letraYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraYActionPerformed
       metodos.anadirLetra("y");
    }//GEN-LAST:event_letraYActionPerformed

    private void letraUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraUActionPerformed
       metodos.anadirLetra("u");
    }//GEN-LAST:event_letraUActionPerformed

    private void letraIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraIActionPerformed
        metodos.anadirLetra("i");
    }//GEN-LAST:event_letraIActionPerformed

    private void letraPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraPActionPerformed
         metodos.anadirLetra("p");
    }//GEN-LAST:event_letraPActionPerformed

    private void letraOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraOActionPerformed
         metodos.anadirLetra("o");
    }//GEN-LAST:event_letraOActionPerformed

    private void letraAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraAActionPerformed
         metodos.anadirLetra("a");
    }//GEN-LAST:event_letraAActionPerformed

    private void letraSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraSActionPerformed
        metodos.anadirLetra("s");
    }//GEN-LAST:event_letraSActionPerformed

    private void letraDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraDActionPerformed
        metodos.anadirLetra("d");
    }//GEN-LAST:event_letraDActionPerformed

    private void letraFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraFActionPerformed
        metodos.anadirLetra("f");
    }//GEN-LAST:event_letraFActionPerformed

    private void letraGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraGActionPerformed
        metodos.anadirLetra("g");
    }//GEN-LAST:event_letraGActionPerformed

    private void letraHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraHActionPerformed
       metodos.anadirLetra("h");
    }//GEN-LAST:event_letraHActionPerformed

    private void letraJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraJActionPerformed
         metodos.anadirLetra("j");
    }//GEN-LAST:event_letraJActionPerformed

    private void letraKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraKActionPerformed
        metodos.anadirLetra("k");
    }//GEN-LAST:event_letraKActionPerformed

    private void letraLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraLActionPerformed
       metodos.anadirLetra("l");
    }//GEN-LAST:event_letraLActionPerformed

    private void letraÑActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraÑActionPerformed
         metodos.anadirLetra("ñ");
    }//GEN-LAST:event_letraÑActionPerformed

    private void letraZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraZActionPerformed
        metodos.anadirLetra("z");
    }//GEN-LAST:event_letraZActionPerformed

    private void letraXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraXActionPerformed
         metodos.anadirLetra("x");
    }//GEN-LAST:event_letraXActionPerformed

    private void letraCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraCActionPerformed
        metodos.anadirLetra("c");
    }//GEN-LAST:event_letraCActionPerformed

    private void letraVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraVActionPerformed
         metodos.anadirLetra("v");
    }//GEN-LAST:event_letraVActionPerformed

    private void letraBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraBActionPerformed
        metodos.anadirLetra("b");
    }//GEN-LAST:event_letraBActionPerformed

    private void letraNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraNActionPerformed
        metodos.anadirLetra("n");
    }//GEN-LAST:event_letraNActionPerformed

    private void letraMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraMActionPerformed
        metodos.anadirLetra("m");
    }//GEN-LAST:event_letraMActionPerformed

    private void botonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonContinuarActionPerformed
        dispose();
    }//GEN-LAST:event_botonContinuarActionPerformed

    private void letraEspacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraEspacioActionPerformed
        metodos.anadirLetra(" ");
    }//GEN-LAST:event_letraEspacioActionPerformed

    private void letraBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraBorrarActionPerformed
       metodos.borrarCaracter();
    }//GEN-LAST:event_letraBorrarActionPerformed

    public StringBuilder getCadena() {
        return cadena;
    }

    public JLabel getTextoIntroducido() {
        return textoIntroducido;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonContinuar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton letraA;
    private javax.swing.JButton letraB;
    private javax.swing.JButton letraBorrar;
    private javax.swing.JButton letraC;
    private javax.swing.JButton letraD;
    private javax.swing.JButton letraE;
    private javax.swing.JButton letraEspacio;
    private javax.swing.JButton letraF;
    private javax.swing.JButton letraG;
    private javax.swing.JButton letraH;
    private javax.swing.JButton letraI;
    private javax.swing.JButton letraJ;
    private javax.swing.JButton letraK;
    private javax.swing.JButton letraL;
    private javax.swing.JButton letraM;
    private javax.swing.JButton letraN;
    private javax.swing.JButton letraO;
    private javax.swing.JButton letraP;
    private javax.swing.JButton letraR;
    private javax.swing.JButton letraS;
    private javax.swing.JButton letraT;
    private javax.swing.JButton letraU;
    private javax.swing.JButton letraV;
    private javax.swing.JButton letraW;
    private javax.swing.JButton letraX;
    private javax.swing.JButton letraY;
    private javax.swing.JButton letraZ;
    private javax.swing.JButton letraq;
    private javax.swing.JButton letraÑ;
    private javax.swing.JLabel textoIntroducido;
    // End of variables declaration//GEN-END:variables
}
