/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package productos.InterfazGrafica.EdicionProductos;

import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import productos.extras.Extra;
import productos.hamburguesas.Hamburguesa;
import productos.ingredientes.Ingrediente;
import productos.interfazPedido.personalizarPedido.extras.PanelExtra;
import productos.productos.Producto;

/**
 *
 * @author aleja
 */
public class PanelEdicionProductos extends javax.swing.JPanel {

    private Producto producto;

    /**
     * Creates new form PanelEdicionProductos
     */
    public PanelEdicionProductos(Producto producto) {
        initComponents();
        mostrarDatosProducto();
        ImageIcon icon = new ImageIcon(producto.getImagenProducto().getPath());
        imagenProducto.setIcon(icon);
    }

    private void mostrarDatosProducto() {
        if (producto instanceof Hamburguesa ham) {
            mostrarIngredientesExtrasProducto(ham.getIngredientes(), ham.getExtras());
        }
        //Actualizamos el panel
        panelIngredientesExtras.revalidate();
        panelIngredientesExtras.repaint();
    }

    private void mostrarIngredientesExtrasProducto(List<Ingrediente> ingredientes, List<Extra> extras) {
        panelIngredientesExtras.setLayout(new BoxLayout(panelIngredientesExtras, BoxLayout.Y_AXIS));
        // Mostramos todos los ingredientes
        for (int i = 0; i < ingredientes.size(); i++) {
            panelIngredientesExtras.add(new PanelIngrediente(ingredientes.get(i), i));
        }
        //Mostramos todos los extras
        for (int i = 0; i < extras.size(); i++) {
            panelIngredientesExtras.add(new PanelExtra(extras.get(i), (ingredientes.size() + i)));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImagenProducto = new javax.swing.JPanel();
        imagenProducto = new javax.swing.JLabel();
        scrollPanelIngredientesExtras = new javax.swing.JScrollPane();
        panelIngredientesExtras = new javax.swing.JPanel();

        setBackground(new java.awt.Color(88, 214, 141));

        panelImagenProducto.setBackground(new java.awt.Color(255, 255, 255));

        imagenProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/productos/InterfazGrafica/imagenesProductos/Imagenes/imageNotFound256.png"))); // NOI18N

        javax.swing.GroupLayout panelImagenProductoLayout = new javax.swing.GroupLayout(panelImagenProducto);
        panelImagenProducto.setLayout(panelImagenProductoLayout);
        panelImagenProductoLayout.setHorizontalGroup(
            panelImagenProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImagenProductoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(imagenProducto)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        panelImagenProductoLayout.setVerticalGroup(
            panelImagenProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImagenProductoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(imagenProducto)
                .addGap(60, 60, 60))
        );

        scrollPanelIngredientesExtras.setBorder(null);

        javax.swing.GroupLayout panelIngredientesExtrasLayout = new javax.swing.GroupLayout(panelIngredientesExtras);
        panelIngredientesExtras.setLayout(panelIngredientesExtrasLayout);
        panelIngredientesExtrasLayout.setHorizontalGroup(
            panelIngredientesExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );
        panelIngredientesExtrasLayout.setVerticalGroup(
            panelIngredientesExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );

        scrollPanelIngredientesExtras.setViewportView(panelIngredientesExtras);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelImagenProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPanelIngredientesExtras, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImagenProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollPanelIngredientesExtras)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagenProducto;
    private javax.swing.JPanel panelImagenProducto;
    private javax.swing.JPanel panelIngredientesExtras;
    private javax.swing.JScrollPane scrollPanelIngredientesExtras;
    // End of variables declaration//GEN-END:variables

}
