package productos.InterfazGrafica.EdicionProductos;

import java.awt.Color;
import java.math.BigDecimal;
import javax.swing.ImageIcon;
import productos.extras.Extra;

/**
 * Esta clase muestra un panel con la informacion sobre el ingrediente junto con
 * la opcion para desactivar o activar el producto
 *
 * @author Alejandro Perellón López
 */
public final class panelExtra extends javax.swing.JPanel {

    private final Extra extra;

    /**
     * Creates new form panelIngrediente
     */
    public panelExtra(Extra ext, int posicionElemento) {
        initComponents();
        this.extra = ext;
        establecerDatosIngrediente();
        establecerColorCasilla(posicionElemento);
    }

    /**
     * Para que el producto sea visiblemente mas bonito segun si la posicion del
     * producto es par o impar se va a modificar el color de fondo del producto
     */
    private void establecerColorCasilla(int posicion) {
        //Si es numero impar se cambia de color
        if (posicion % 2 != 0) {
            this.setBackground(Color.decode("#a9dfbf"));
        }
    }

    /**
     * Este metodo establece los datos del extra en el panel, entre los datos
     * incluye la cantidad de producto adicional, un selector de cantidades
     * adicionales y el coste adicional del producto
     */
    public void establecerDatosIngrediente() {
        //Establecemos la imagen del producto
        ImageIcon icon = new ImageIcon(extra.getRutaImagen());
        imagenIngrediente.setIcon(icon);
        //Establecemos el nombre del ingrediente
        nombreIngrediente.setText(extra.getRutaImagen());
        //Establecemos la cantidad de producto
        cantidadProducto.setText(String.valueOf(extra.getCantidadExtra()));
        //Establecemos el coste adicional
        establecerCosteAdicional();

    }

    private void cambiarCantidadProducto(boolean aumentarCantidad) {
        //Si aumentarCantidad es TRUE se aumenta la cantidad de producto
        if (aumentarCantidad) {
            extra.setCantidadExtra(extra.getCantidadExtra() + 1);
        } // Si aumentar cantidad es FALSE se disminuye la cantidad de extra
        else {
            extra.setCantidadExtra(extra.getCantidadExtra() - 1);
        }

        //Establecemos la cantidad de producto
        cantidadProducto.setText(String.valueOf(extra.getCantidadExtra()));

        //Establecemos los botones si llega a uno de los limites
        controlarBotonesCantidad();

        //Establecemos el coste adicional
        establecerCosteAdicional();
    }

    /**
     * Este metodo controla los botones de aumentar o disminuir la cantidad de
     * producto, en caso de que se iguale la cantidad maxima el boton de
     * aumentar de inabilita, en caso de que la cantidad sea 0 la cantidad de
     * producto se desactiva el boton de disminuir
     */
    private void controlarBotonesCantidad() {
        //Activamos los botones de aumentar y disminuir
        aumentarCantidad.setEnabled(true);
        disminuirCantidad.setEnabled(true);

        //Comprobamos si se iguala la cantidad maxima y se desHabilita el boton
        if (extra.getCantidadExtra() >= extra.getMaximoExtras()) {
            aumentarCantidad.setEnabled(false);
        }
        //Comprobamos si la cantidad de extra son
        if (extra.getCantidadExtra() <= 0) {
            disminuirCantidad.setEnabled(false);
        }

    }

    /**
     * Este metodo establece el coste adicional segun la cantidad de producto
     * que adquiramos
     */
    private void establecerCosteAdicional() {
        // Convetimos la cantidad de extra en un bigdecimal
        BigDecimal cantidadExtra = new BigDecimal(extra.getCantidadExtra());
        // Realizamos el calculo de la cantidad de extra por el coste extra
        BigDecimal resultado = cantidadExtra.multiply(extra.getCosteExtra());
        // Establecemos el coste extra
        costeAdicional.setText(resultado.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagenIngrediente = new javax.swing.JLabel();
        nombreIngrediente = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        aumentarCantidad = new javax.swing.JButton();
        disminuirCantidad = new javax.swing.JButton();
        cantidadProducto = new javax.swing.JLabel();
        costeAdicional = new javax.swing.JLabel();

        setBackground(new java.awt.Color(88, 214, 141));

        imagenIngrediente.setBackground(new java.awt.Color(255, 255, 255));
        imagenIngrediente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenIngrediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/productos/InterfazGrafica/imagenesProductos/Imagenes/imageNotFound64.png"))); // NOI18N
        imagenIngrediente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        imagenIngrediente.setOpaque(true);

        nombreIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombreIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        nombreIngrediente.setText("Sample text");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        aumentarCantidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aumentarCantidad.setText("▲");
        aumentarCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aumentarCantidadActionPerformed(evt);
            }
        });

        disminuirCantidad.setText("▼");
        disminuirCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disminuirCantidadActionPerformed(evt);
            }
        });

        cantidadProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cantidadProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidadProducto.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aumentarCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(disminuirCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aumentarCantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disminuirCantidad)
                .addContainerGap())
        );

        costeAdicional.setBackground(new java.awt.Color(255, 255, 255));
        costeAdicional.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        costeAdicional.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        costeAdicional.setText("+0,00");
        costeAdicional.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(costeAdicional, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(costeAdicional, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imagenIngrediente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void aumentarCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aumentarCantidadActionPerformed
        cambiarCantidadProducto(true);
    }//GEN-LAST:event_aumentarCantidadActionPerformed

    private void disminuirCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disminuirCantidadActionPerformed
        cambiarCantidadProducto(false);
    }//GEN-LAST:event_disminuirCantidadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aumentarCantidad;
    private javax.swing.JLabel cantidadProducto;
    private javax.swing.JLabel costeAdicional;
    private javax.swing.JButton disminuirCantidad;
    private javax.swing.JLabel imagenIngrediente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreIngrediente;
    // End of variables declaration//GEN-END:variables
}
