package productos.InterfazGrafica.EdicionProductos;

import java.awt.Color;
import javax.swing.ImageIcon;
import productos.ingredientes.Ingrediente;

/**
 * Esta clase muestra un panel con la informacion sobre el ingrediente junto con
 * la opcion para desactivar o activar el producto
 *
 * @author Alejandro Perellón López
 */
public final class panelIngrediente extends javax.swing.JPanel {

    private final Ingrediente ingrediente;

    /**
     * Creates new form panelIngrediente
     */
    public panelIngrediente(Ingrediente ing, int posicionElemento) {
        initComponents();
        this.ingrediente = ing;
        establecerDatosIngrediente();
        establecerColorCasilla(posicionElemento);
    }

    /**
     * Para que el producto sea visiblemente mas bonito segun si la posicion del
     * producto es par o impar se va a modificar el color de fondo del producto
     */
    private void establecerColorCasilla(int posicion) {
        //Si es numero impar se cambia de color
        if (posicion % 2 != 0) {
            this.setBackground(Color.decode("#a9dfbf"));
        }
    }

    /**
     * Este metodo establece los datos del ingrediente en el panel, entre ellos
     * el estado del ingrediente (activo o no), imagen y nomnbre
     */
    public void establecerDatosIngrediente() {
        //Establecemos la imagen del producto
        ImageIcon icon = new ImageIcon(ingrediente.getRutaIngredientes());
        imagenIngrediente.setIcon(icon);
        //Establecemos el nombre del ingrediente
        nombreIngrediente.setText(ingrediente.getNombreIngrediente());
        //Establecemos si esta activo o no
        actualizarEstadoProducto();

    }

    /**
     * Este metodo establece el icono que indica si esta activo o inactivo
     */
    private void actualizarEstadoProducto() {
        ImageIcon icon = new ImageIcon("\\productos\\InterfazGrafica\\EdicionProductos\\inactivo2.png");
        if (ingrediente.isActivo()) {
            icon = new ImageIcon("\\productos\\InterfazGrafica\\EdicionProductos\\activo2.png");
        }
        //Establecemos el estado del ingrediente
        cuadroEstadoIngrediente.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagenIngrediente = new javax.swing.JLabel();
        nombreIngrediente = new javax.swing.JLabel();
        cuadroEstadoIngrediente = new javax.swing.JLabel();

        setBackground(new java.awt.Color(88, 214, 141));

        imagenIngrediente.setBackground(new java.awt.Color(255, 255, 255));
        imagenIngrediente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenIngrediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/productos/InterfazGrafica/imagenesProductos/Imagenes/imageNotFound64.png"))); // NOI18N
        imagenIngrediente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        imagenIngrediente.setOpaque(true);

        nombreIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombreIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        nombreIngrediente.setText("Sample text");

        cuadroEstadoIngrediente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadroEstadoIngrediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/productos/InterfazGrafica/EdicionProductos/activo2.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cuadroEstadoIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imagenIngrediente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(cuadroEstadoIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cuadroEstadoIngrediente;
    private javax.swing.JLabel imagenIngrediente;
    private javax.swing.JLabel nombreIngrediente;
    // End of variables declaration//GEN-END:variables

}
