package caja.interfazCaja.panelPrincipalCaja;

import caja.modelo.Caja;
import javax.swing.JLabel;
import java.awt.Color;

/**
 * Interfaz grafica que representa la informacion basica de la caja
 *
 * @author Alejandro Perellón López
 */
public class PanelCaja extends javax.swing.JPanel {

    private Caja caja;

    /**
     * Creates new form PanelCaja
     */
    public PanelCaja(Caja caja) {
        initComponents();
        this.caja = caja;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        extadoConexion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fechaHora = new javax.swing.JLabel();
        datosEmpleado = new javax.swing.JLabel();
        PuestoSesion = new javax.swing.JLabel();
        estadoCaja = new javax.swing.JLabel();
        tiempoPedido = new javax.swing.JLabel();
        textoConexion = new javax.swing.JLabel();
        estadoConexion = new javax.swing.JLabel();

        extadoConexion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        extadoConexion.setText("Estado conexion:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(Color.RED);
        jLabel1.setText("Desconectado");

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        fechaHora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fechaHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechaHora.setText("00/00/2000   00:00:00");

        datosEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        datosEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        datosEmpleado.setText("No hay usuario activo");

        PuestoSesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PuestoSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PuestoSesion.setText("Puesto X | Sesion X");

        estadoCaja.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        estadoCaja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estadoCaja.setText("Cerrada");

        tiempoPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tiempoPedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tiempoPedido.setText("00:00");

        textoConexion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoConexion.setText("Estado conexion:");

        estadoConexion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        estadoConexion.setForeground(Color.ORANGE);
        estadoConexion.setText("Estableciendo conexion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tiempoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(datosEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PuestoSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(estadoCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textoConexion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estadoConexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(estadoConexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textoConexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fechaHora)
                        .addComponent(datosEmpleado)
                        .addComponent(PuestoSesion)
                        .addComponent(estadoCaja)
                        .addComponent(tiempoPedido)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public Caja getCaja() {
        return caja;
    }

    public JLabel getDatosEmpleado() {
        return datosEmpleado;
    }

    public JLabel getPuestoSesion() {
        return PuestoSesion;
    }

    public JLabel getEstadoCaja() {
        return estadoCaja;
    }

    public JLabel getFechaHora() {
        return fechaHora;
    }

    public JLabel getTiempoPedido() {
        return tiempoPedido;
    }

    public JLabel getEstadoConexion() {
        return estadoConexion;
    }

  

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PuestoSesion;
    private javax.swing.JLabel datosEmpleado;
    private javax.swing.JLabel estadoCaja;
    private javax.swing.JLabel estadoConexion;
    private javax.swing.JLabel extadoConexion;
    private javax.swing.JLabel fechaHora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel textoConexion;
    private javax.swing.JLabel tiempoPedido;
    // End of variables declaration//GEN-END:variables
}
