package auxiliares.solicitarDatos.solicitudInicioSesion.interfazInicioSesion.DireccionYUsuario;

import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 * Metodo que muestra en interfaz grafica la peticion de datos de usuario para
 * realizar la conexion
 *
 * @author Alejandro Perellón López
 */
public class DireccionYUsuarioInterfaz extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DireccionYUsuarioInterfaz.class.getName());

    private DireccionYUsuarioInterfazMetodos metodos;

    /**
     * Creates new form DireccionYUsuarioInterfaz
     */
    public DireccionYUsuarioInterfaz(java.awt.Frame parent, boolean modal, DireccionYUsuarioInterfazMetodos metodos) {
        super(parent, modal);
        this.metodos = metodos;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonAceptar1 = new javax.swing.JButton();
        direccionIP = new javax.swing.JTextField();
        puerto = new javax.swing.JTextField();
        usuario = new javax.swing.JTextField();
        contrasena = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        botonAceptar1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botonAceptar1.setText("Aceptar");
        botonAceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptar1ActionPerformed(evt);
            }
        });

        direccionIP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        direccionIP.setToolTipText("Introduce la direccion IP");
        direccionIP.setBorder(javax.swing.BorderFactory.createTitledBorder("DIRECCION IP"));

        puerto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        puerto.setToolTipText("Introduce puerto de conexion");
        puerto.setBorder(javax.swing.BorderFactory.createTitledBorder("PUERTO"));

        usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usuario.setToolTipText("Introduce nombre de usuario");
        usuario.setBorder(javax.swing.BorderFactory.createTitledBorder("USUARIO"));

        contrasena.setToolTipText("Introduce la contraseña de usuario");
        contrasena.setBorder(javax.swing.BorderFactory.createTitledBorder("CONTRASEÑA"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 122, Short.MAX_VALUE)
                        .addComponent(botonAceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(contrasena, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(direccionIP, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(puerto)
                            .addComponent(usuario, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(direccionIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(puerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonAceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptar1ActionPerformed
        dispose();
    }//GEN-LAST:event_botonAceptar1ActionPerformed

    public JPasswordField getContrasena() {
        return contrasena;
    }

    public JTextField getDireccionIP() {
        return direccionIP;
    }

    public JTextField getPuerto() {
        return puerto;
    }

    public JTextField getUsuario() {
        return usuario;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar1;
    private javax.swing.JPasswordField contrasena;
    private javax.swing.JTextField direccionIP;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField puerto;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
