package productos.interfazPedido.casillaProducto;

import javax.swing.JLabel;
import pedido.modelo.Pedido;
import productos.modelo.Producto;

/**
 * Esta clase muestra un panel con la informacion de un producto, entre la
 * informacion muestra una imagen, el nombre del producto y el precio del mismo
 *
 * @author Alejandro Perellón López
 */
public class CasillaProducto extends javax.swing.JPanel {

    private final Producto producto;
    private Pedido pedido;
    // Es la clase de metodos que se va a utilizar para realizar las modificaciones
    private CasillaProductoMetodos metodo = new CasillaProductoMetodos(this);

    /**
     * Constructor que inicia el objeto
     *
     * @param producto es el producto al que va a representar la casilla
     * @param pedido es el pedido en el que se van a añadir productos o no
     */
    public CasillaProducto(Producto producto, Pedido pedido) {
        this.producto = producto;
        this.pedido = pedido;
        
        initComponents(); 
        metodo.establecerDatosProducto(producto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoPrecio = new javax.swing.JLabel();
        cuadroImagen = new javax.swing.JLabel();
        textoNombre = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        setMaximumSize(new java.awt.Dimension(256, 105));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        textoPrecio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textoPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoPrecio.setText("€ 0,00");

        cuadroImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficaErrorProducto/imageNotFound64.png"))); // NOI18N

        textoNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textoNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoNombre.setText("Sample text");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cuadroImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 129, Short.MAX_VALUE)
                        .addComponent(textoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoPrecio))
                    .addComponent(cuadroImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este metodo se activa cuando se realiza click en cualquier parte del
     * panel, tras la`pulsacion realiza la insercion del producto en el pedido
     * principal de {@link PanelPedido}
     *
     * @param evt el evento de activa cuando se pulsa en cualquier parte del
     * panel
     */
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        metodo.anadirProductoPedido();
    }//GEN-LAST:event_formMouseClicked

    public Producto getProducto() {
        return producto;
    }

    public JLabel getCuadroImagen() {
        return cuadroImagen;
    }

    public JLabel getTextoNombre() {
        return textoNombre;
    }

    public JLabel getTextoPrecio() {
        return textoPrecio;
    }

    public Pedido getPedido() {
        return pedido;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cuadroImagen;
    private javax.swing.JLabel textoNombre;
    private javax.swing.JLabel textoPrecio;
    // End of variables declaration//GEN-END:variables

}
