package caja.interfazCaja.panelCobro;

import auxiliares.singleton.ClasesEstaticas;
import auxiliares.utilidadesGraficas.coloresInterfaz.ColoresInterfaz;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import pedido.modelo.Pedido;
import productos.interfazProducto.listaProductosPedidos.ToStringRenderer;

/**
 * Clase que muestra el panel de la interfaz grafica del sistema de cobro
 *
 * @author Alejandro Perellón López
 */
public class InterfazCobro extends javax.swing.JPanel {

    private BigDecimal cantidadPropuesta = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
    private MetodosInterfazCobro metodo = new MetodosInterfazCobro(this);
    private DefaultListModel<Object> modeloLista = ClasesEstaticas.getPanelPedido().getModeloLista();

    /**
     * Creates new form InterfazCobro
     */
    public InterfazCobro(Pedido pedido) {
        initComponents();
        //Actualizamos la pantalla para mostrar los valores iniciales
        metodo.actualizarPantalla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonBorrar = new javax.swing.JButton();
        botonPromo = new javax.swing.JButton();
        botonBillete10 = new javax.swing.JButton();
        botonBillete5 = new javax.swing.JButton();
        botonBillete50 = new javax.swing.JButton();
        botonBillete20 = new javax.swing.JButton();
        botonDesc = new javax.swing.JButton();
        textoTotalPagar = new javax.swing.JLabel();
        textoCantidadTotalPagar = new javax.swing.JLabel();
        textoPagado = new javax.swing.JLabel();
        textoCantidadPagado = new javax.swing.JLabel();
        boton1 = new javax.swing.JButton();
        textoBilletes = new javax.swing.JLabel();
        boton2 = new javax.swing.JButton();
        importeExacto = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        botonCobrar = new javax.swing.JButton();
        botonContinuar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaProductosPedidos = new javax.swing.JList<>();
        botonEditarPedido = new javax.swing.JButton();
        botonReintentarCobro = new javax.swing.JButton();
        textoDescuento = new javax.swing.JLabel();
        textoCantidadDescuento = new javax.swing.JLabel();

        setBackground(ColoresInterfaz.SECUNDARIO_CHAMPAGNE);

        botonBorrar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        botonBorrar.setText("Borrar");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        botonPromo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        botonPromo.setText("PROMO");
        botonPromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPromoActionPerformed(evt);
            }
        });

        botonBillete10.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        botonBillete10.setText("10");
        botonBillete10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBillete10ActionPerformed(evt);
            }
        });

        botonBillete5.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        botonBillete5.setText("5");
        botonBillete5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBillete5ActionPerformed(evt);
            }
        });

        botonBillete50.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        botonBillete50.setText("50");
        botonBillete50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBillete50ActionPerformed(evt);
            }
        });

        botonBillete20.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        botonBillete20.setText("20");
        botonBillete20.setToolTipText("");
        botonBillete20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBillete20ActionPerformed(evt);
            }
        });

        botonDesc.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        botonDesc.setText("DESC");
        botonDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDescActionPerformed(evt);
            }
        });

        textoTotalPagar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoTotalPagar.setText("TOTAL PAGAR:");

        textoCantidadTotalPagar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoCantidadTotalPagar.setText("Cantidad1");

        textoPagado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoPagado.setText("PAGADO:");

        textoCantidadPagado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoCantidadPagado.setText("Cantidad2");

        boton1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        boton1.setText("1");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });

        textoBilletes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoBilletes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoBilletes.setText("SELECCIONA EL BILLETE");

        boton2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        boton2.setText("2");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });

        importeExacto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        importeExacto.setText("<html>Importe<br>exacto</html> ");
        importeExacto.setToolTipText("");
        importeExacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importeExactoActionPerformed(evt);
            }
        });

        boton3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        boton3.setText("3");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });

        boton5.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        boton5.setText("5");
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });

        boton6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        boton6.setText("6");
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });

        boton4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        boton4.setText("4");
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });

        boton8.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        boton8.setText("8");
        boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton8ActionPerformed(evt);
            }
        });

        boton9.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        boton9.setText("9");
        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });

        boton7.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        boton7.setText("7");
        boton7.setToolTipText("");
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });

        boton0.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        boton0.setText("0");
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });

        botonCobrar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        botonCobrar.setText("Cobrar");
        botonCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCobrarActionPerformed(evt);
            }
        });

        botonContinuar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botonContinuar.setText("Continuar");
        botonContinuar.setToolTipText("");
        botonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonContinuarActionPerformed(evt);
            }
        });

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setPreferredSize(new java.awt.Dimension(250, 690));

        listaProductosPedidos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        listaProductosPedidos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        listaProductosPedidos.setModel(modeloLista);
        listaProductosPedidos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaProductosPedidos.setCellRenderer(new ToStringRenderer<>());
        jScrollPane3.setViewportView(listaProductosPedidos);

        botonEditarPedido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonEditarPedido.setText("Editar pedido");
        botonEditarPedido.setToolTipText("");
        botonEditarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarPedidoActionPerformed(evt);
            }
        });

        botonReintentarCobro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonReintentarCobro.setText("<html>Reintentar<br>cobro</html> ");
        botonReintentarCobro.setToolTipText("");
        botonReintentarCobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReintentarCobroActionPerformed(evt);
            }
        });

        textoDescuento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoDescuento.setText("DESCUENTO:");

        textoCantidadDescuento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoCantidadDescuento.setText("Cantidad2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoPagado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoCantidadPagado))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(boton7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(boton8, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(boton9, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(boton5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(boton6, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(textoTotalPagar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textoCantidadTotalPagar)
                                    .addGap(46, 46, 46))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(botonReintentarCobro, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(boton0, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(botonCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(botonEditarPedido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(botonBillete20, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(botonBillete50, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(botonBillete5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(botonBillete10, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(textoBilletes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(importeExacto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoDescuento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoCantidadDescuento)))
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoCantidadTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPagado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoCantidadPagado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoCantidadDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botonDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textoBilletes)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton0, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonBorrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonBillete5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonBillete10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonBillete20, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonBillete50, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(importeExacto, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEditarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonReintentarCobro, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        metodo.borrarCantidad();
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonBillete10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBillete10ActionPerformed
        metodo.billetes(10);
    }//GEN-LAST:event_botonBillete10ActionPerformed

    private void botonBillete5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBillete5ActionPerformed
        metodo.billetes(5);
    }//GEN-LAST:event_botonBillete5ActionPerformed

    private void botonBillete50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBillete50ActionPerformed
        metodo.billetes(50);
    }//GEN-LAST:event_botonBillete50ActionPerformed

    private void botonBillete20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBillete20ActionPerformed
        metodo.billetes(20);
    }//GEN-LAST:event_botonBillete20ActionPerformed

    private void botonDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDescActionPerformed
        metodo.establecerDescuento();
    }//GEN-LAST:event_botonDescActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        metodo.introducirNumero(1);
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        metodo.introducirNumero(2);
    }//GEN-LAST:event_boton2ActionPerformed

    private void importeExactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importeExactoActionPerformed
        metodo.importeExacto();
    }//GEN-LAST:event_importeExactoActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        metodo.introducirNumero(3);
    }//GEN-LAST:event_boton3ActionPerformed

    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed
        metodo.introducirNumero(5);
    }//GEN-LAST:event_boton5ActionPerformed

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
        metodo.introducirNumero(6);
    }//GEN-LAST:event_boton6ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
        metodo.introducirNumero(4);
    }//GEN-LAST:event_boton4ActionPerformed

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed
        metodo.introducirNumero(8);
    }//GEN-LAST:event_boton8ActionPerformed

    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed
        metodo.introducirNumero(9);
    }//GEN-LAST:event_boton9ActionPerformed

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
        metodo.introducirNumero(7);
    }//GEN-LAST:event_boton7ActionPerformed

    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed
        metodo.introducirNumero(0);
    }//GEN-LAST:event_boton0ActionPerformed

    private void botonCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCobrarActionPerformed
        metodo.cobrarOperacion();
    }//GEN-LAST:event_botonCobrarActionPerformed

    private void botonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonContinuarActionPerformed
        metodo.continuar();
    }//GEN-LAST:event_botonContinuarActionPerformed

    private void botonPromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPromoActionPerformed
        metodo.promocionarArticulo();
    }//GEN-LAST:event_botonPromoActionPerformed

    private void botonEditarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarPedidoActionPerformed
        metodo.editarPedido();
    }//GEN-LAST:event_botonEditarPedidoActionPerformed

    private void botonReintentarCobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReintentarCobroActionPerformed
       metodo.reintentarCobro();
    }//GEN-LAST:event_botonReintentarCobroActionPerformed

    public BigDecimal getCantidadPropuesta() {
        return cantidadPropuesta;
    }

    public MetodosInterfazCobro getMetodo() {
        return metodo;
    }

    public JButton getBoton0() {
        return boton0;
    }

    public JButton getBoton1() {
        return boton1;
    }

    public JButton getBoton2() {
        return boton2;
    }

    public JButton getBoton3() {
        return boton3;
    }

    public JButton getBoton4() {
        return boton4;
    }

    public JButton getBoton5() {
        return boton5;
    }

    public JButton getBoton6() {
        return boton6;
    }

    public JButton getBoton7() {
        return boton7;
    }

    public JButton getBoton8() {
        return boton8;
    }

    public JButton getBoton9() {
        return boton9;
    }

    public JButton getBotonBillete10() {
        return botonBillete10;
    }

    public JButton getBotonBillete20() {
        return botonBillete20;
    }

    public JButton getBotonBillete5() {
        return botonBillete5;
    }

    public JButton getBotonBillete50() {
        return botonBillete50;
    }

    public JButton getBotonBorrar() {
        return botonBorrar;
    }

    public JButton getBotonCobrar() {
        return botonCobrar;
    }

    public JButton getBotonDesc() {
        return botonDesc;
    }

    public JButton getBotonPromo() {
        return botonPromo;
    }

    public JButton getImporteExacto() {
        return importeExacto;
    }

    public JLabel getTextoBilletes() {
        return textoBilletes;
    }

    public JLabel getTextoCantidadPagado() {
        return textoCantidadPagado;
    }

    public JLabel getTextoCantidadTotalPagar() {
        return textoCantidadTotalPagar;
    }

    public JLabel getTextoPagado() {
        return textoPagado;
    }

    public JLabel getTextoTotalPagar() {
        return textoTotalPagar;
    }

    public JButton getBotonContinuar() {
        return botonContinuar;
    }

    public void setCantidadPropuesta(BigDecimal cantidadPropuesta) {
        this.cantidadPropuesta = cantidadPropuesta;
    }

    public DefaultListModel<Object> getModeloLista() {
        return modeloLista;
    }

    public JList<Object> getListaProductosPedidos() {
        return listaProductosPedidos;
    }

    public JButton getBotonEditarPedido() {
        return botonEditarPedido;
    }

    public JButton getBotonVolverCobrar() {
        return botonReintentarCobro;
    }

    public JLabel getTextoCantidadDescuento() {
        return textoCantidadDescuento;
    }

    public JLabel getTextoDescuento() {
        return textoDescuento;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JButton botonBillete10;
    private javax.swing.JButton botonBillete20;
    private javax.swing.JButton botonBillete5;
    private javax.swing.JButton botonBillete50;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonCobrar;
    private javax.swing.JButton botonContinuar;
    private javax.swing.JButton botonDesc;
    private javax.swing.JButton botonEditarPedido;
    private javax.swing.JButton botonPromo;
    private javax.swing.JButton botonReintentarCobro;
    private javax.swing.JButton importeExacto;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<Object> listaProductosPedidos;
    private javax.swing.JLabel textoBilletes;
    private javax.swing.JLabel textoCantidadDescuento;
    private javax.swing.JLabel textoCantidadPagado;
    private javax.swing.JLabel textoCantidadTotalPagar;
    private javax.swing.JLabel textoDescuento;
    private javax.swing.JLabel textoPagado;
    private javax.swing.JLabel textoTotalPagar;
    // End of variables declaration//GEN-END:variables
}
