package productos.interfazPedido.personalizarPedido.ingredientes;

import javax.swing.JButton;
import javax.swing.JLabel;
import productos.modelo.Ingrediente;

/**
 * Esta clase muestra un panel con la informacion sobre el ingrediente junto con
 * la opcion para desactivar o activar el producto
 *
 * @author Alejandro Perellón López
 */
public final class PanelIngrediente extends javax.swing.JPanel {

    private Ingrediente ingrediente;

    private PanelIngredienteMetodos metodos = new PanelIngredienteMetodos(this, ingrediente);

    /**
     * Creates new form panelIngrediente
     */
    public PanelIngrediente(Ingrediente ing, boolean posicion) {
        initComponents();
        this.ingrediente = ing;
       metodos.iniciarPanelIngrediente(posicion);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagenIngrediente = new javax.swing.JLabel();
        nombreIngrediente = new javax.swing.JLabel();
        cuadroEstadoIngrediente = new javax.swing.JButton();

        setBackground(new java.awt.Color(88, 214, 141));

        imagenIngrediente.setBackground(new java.awt.Color(255, 255, 255));
        imagenIngrediente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenIngrediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficaErrorProducto/imageNotFound64.png"))); // NOI18N
        imagenIngrediente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        imagenIngrediente.setOpaque(true);

        nombreIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombreIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        nombreIngrediente.setText("Sample text");

        cuadroEstadoIngrediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficaPersonalizarProducto/inactivo.png"))); // NOI18N
        cuadroEstadoIngrediente.setBorder(null);
        cuadroEstadoIngrediente.setBorderPainted(false);
        cuadroEstadoIngrediente.setContentAreaFilled(false);
        cuadroEstadoIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadroEstadoIngredienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cuadroEstadoIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imagenIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(cuadroEstadoIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cuadroEstadoIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadroEstadoIngredienteActionPerformed
        metodos.cambiarEstadoIngrediente();
    }//GEN-LAST:event_cuadroEstadoIngredienteActionPerformed

    public Ingrediente getIngrediente() {
        return ingrediente;
    }

    public PanelIngredienteMetodos getMetodos() {
        return metodos;
    }

    public JLabel getImagenIngrediente() {
        return imagenIngrediente;
    }

    public JLabel getNombreIngrediente() {
        return nombreIngrediente;
    }

    public JButton getCuadroEstadoIngrediente() {
        return cuadroEstadoIngrediente;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cuadroEstadoIngrediente;
    private javax.swing.JLabel imagenIngrediente;
    private javax.swing.JLabel nombreIngrediente;
    // End of variables declaration//GEN-END:variables

}
