package caja.interfazCaja.panelAccionesCaja;

import auxiliares.utilidadesGraficas.coloresInterfaz.ColoresInterfaz;
import empleados.util.ActividadEmpleados;
import javax.swing.JButton;
import javax.swing.JCheckBox;

/**
 * Clase de interfaz grafica que muestra diferentes acciones a realizar en la
 * caja
 *
 * @author Alejandro Perellón López
 */
public class AccionesSobreCaja extends javax.swing.JPanel {

    private AccionesSobreCajaMetodos metodos = new AccionesSobreCajaMetodos(this);

    /**
     * Creates new form AccionesSobreCaja
     */
    public AccionesSobreCaja() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        iniciarCaja = new javax.swing.JButton();
        cerrarCaja = new javax.swing.JButton();
        estadisticasVentas = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        activarProductos = new javax.swing.JButton();
        pantallaPrincipla = new javax.swing.JButton();
        CerrarAplicacion = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        actualizarImagenesServidor = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        activarProductos2 = new javax.swing.JButton();
        checkReintentarConexion = new javax.swing.JCheckBox();
        forzarConexionServidor = new javax.swing.JButton();
        forzarDesconexion = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cancelarPedido = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1366, 550));

        panelPrincipal.setBackground(ColoresInterfaz.SECUNDARIO_CHAMPAGNE);
        panelPrincipal.setPreferredSize(new java.awt.Dimension(1366, 550));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Selecciona una accion de caja");

        iniciarCaja.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iniciarCaja.setText("Iniciar caja");
        iniciarCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarCajaActionPerformed(evt);
            }
        });

        cerrarCaja.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cerrarCaja.setText("Cerrar caja");
        cerrarCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarCajaActionPerformed(evt);
            }
        });

        estadisticasVentas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        estadisticasVentas.setText("Consultar estadisticas");
        estadisticasVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadisticasVentasActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Selecciona una accion de inventario");

        activarProductos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        activarProductos.setText("Modificar stock productos");
        activarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activarProductosActionPerformed(evt);
            }
        });

        pantallaPrincipla.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pantallaPrincipla.setText("Volver pantalla principal");
        pantallaPrincipla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pantallaPrinciplaActionPerformed(evt);
            }
        });

        CerrarAplicacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CerrarAplicacion.setText("Cerrar la aplicacion");
        CerrarAplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarAplicacionActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Selecciona una accion de productos");

        actualizarImagenesServidor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        actualizarImagenesServidor.setText("Actualizar imagenes productos");
        actualizarImagenesServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarImagenesServidorActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Selecciona una accion de servidor");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Selecciona una accion de logs");

        activarProductos2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        activarProductos2.setText("Abrir los logs de la aplicacion");
        activarProductos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activarProductos2ActionPerformed(evt);
            }
        });

        checkReintentarConexion.setBackground(ColoresInterfaz.SECUNDARIO_CHAMPAGNE);
        checkReintentarConexion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        checkReintentarConexion.setSelected(true);
        checkReintentarConexion.setText("Reintentar conexion al servidor");
        checkReintentarConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkReintentarConexionActionPerformed(evt);
            }
        });

        forzarConexionServidor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        forzarConexionServidor.setText("Forzar conexion al servidor");
        forzarConexionServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forzarConexionServidorActionPerformed(evt);
            }
        });

        forzarDesconexion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        forzarDesconexion.setText("Forzar desconexion al servidor");
        forzarDesconexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forzarDesconexionActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Selecciona una accion del pedido");

        cancelarPedido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelarPedido.setText("Cancelar pedido");
        cancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(estadisticasVentas, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                        .addComponent(cerrarCaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                        .addComponent(iniciarCaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                            .addComponent(activarProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                            .addComponent(checkReintentarConexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(forzarConexionServidor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(forzarDesconexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(actualizarImagenesServidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(51, 51, 51))
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(activarProductos2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(CerrarAplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pantallaPrincipla, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(iniciarCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cerrarCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(estadisticasVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(activarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(actualizarImagenesServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(checkReintentarConexion)
                                .addGap(0, 0, 0)
                                .addComponent(forzarConexionServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(activarProductos2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(forzarDesconexion, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pantallaPrincipla, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CerrarAplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1410, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarCajaActionPerformed
        metodos.iniciarCaja();
    }//GEN-LAST:event_iniciarCajaActionPerformed

    private void cerrarCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarCajaActionPerformed
        metodos.cerrarCaja();
    }//GEN-LAST:event_cerrarCajaActionPerformed

    private void estadisticasVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadisticasVentasActionPerformed
        metodos.consultarEstadisticasVentas();
    }//GEN-LAST:event_estadisticasVentasActionPerformed

    private void activarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activarProductosActionPerformed
        metodos.cambiarEstockProductos();
    }//GEN-LAST:event_activarProductosActionPerformed

    private void pantallaPrinciplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pantallaPrinciplaActionPerformed
        metodos.volverPantallaPrincipal();
    }//GEN-LAST:event_pantallaPrinciplaActionPerformed

    private void CerrarAplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarAplicacionActionPerformed
        if (new ActividadEmpleados().solicitarPermisos("Introduce el numero de empleado", 2)) {
            System.exit(0);
        }
    }//GEN-LAST:event_CerrarAplicacionActionPerformed

    private void actualizarImagenesServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarImagenesServidorActionPerformed
        metodos.actualizarImagenesServidor();
    }//GEN-LAST:event_actualizarImagenesServidorActionPerformed

    private void activarProductos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activarProductos2ActionPerformed
        metodos.abrirLogsServidor();
    }//GEN-LAST:event_activarProductos2ActionPerformed

    private void forzarConexionServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forzarConexionServidorActionPerformed
        metodos.forzarConexionServidor();
    }//GEN-LAST:event_forzarConexionServidorActionPerformed

    private void checkReintentarConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkReintentarConexionActionPerformed
        metodos.actualizarReconexionAutomatica();
    }//GEN-LAST:event_checkReintentarConexionActionPerformed

    private void forzarDesconexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forzarDesconexionActionPerformed
        metodos.desconectarDelServidor();
    }//GEN-LAST:event_forzarDesconexionActionPerformed

    private void cancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarPedidoActionPerformed
        metodos.cancelarPedido();
    }//GEN-LAST:event_cancelarPedidoActionPerformed

    public JButton getActivarProductos() {
        return activarProductos;
    }

    public JButton getCerrarCaja() {
        return cerrarCaja;
    }

    public JButton getEstadisticasVentas() {
        return estadisticasVentas;
    }

    public JButton getIniciarCaja() {
        return iniciarCaja;
    }

    public JCheckBox getCheckReintentarConexion() {
        return checkReintentarConexion;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CerrarAplicacion;
    private javax.swing.JButton activarProductos;
    private javax.swing.JButton activarProductos2;
    private javax.swing.JButton actualizarImagenesServidor;
    private javax.swing.JButton cancelarPedido;
    private javax.swing.JButton cerrarCaja;
    private javax.swing.JCheckBox checkReintentarConexion;
    private javax.swing.JButton estadisticasVentas;
    private javax.swing.JButton forzarConexionServidor;
    private javax.swing.JButton forzarDesconexion;
    private javax.swing.JButton iniciarCaja;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JButton pantallaPrincipla;
    // End of variables declaration//GEN-END:variables
}
