package caja.interfazCaja.panelAccionesCaja;

import empleados.util.ActividadEmpleados;
import javax.swing.JButton;

/**
 * Clase de interfaz grafica que muestra diferentes acciones a realizar en la
 * caja
 *
 * @author Alejandro Perellón López
 */
public class AccionesSobreCaja extends javax.swing.JPanel {

    private AccionesSobreCajaMetodos metodos = new AccionesSobreCajaMetodos(this);

    /**
     * Creates new form AccionesSobreCaja
     */
    public AccionesSobreCaja() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        iniciarCaja = new javax.swing.JButton();
        cerrarCaja = new javax.swing.JButton();
        estadisticasVentas = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        activarProductos = new javax.swing.JButton();
        desactivarProductos = new javax.swing.JButton();
        consultarProductos = new javax.swing.JButton();
        pantallaPrincipla = new javax.swing.JButton();
        CerrarAplicacion = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1366, 550));

        panelPrincipal.setBackground(new java.awt.Color(244, 241, 226));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(1366, 550));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Selecciona una accion de caja");

        iniciarCaja.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iniciarCaja.setText("Iniciar caja");
        iniciarCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarCajaActionPerformed(evt);
            }
        });

        cerrarCaja.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cerrarCaja.setText("Cerrar caja");
        cerrarCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarCajaActionPerformed(evt);
            }
        });

        estadisticasVentas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        estadisticasVentas.setText("Consultar estadisticas");
        estadisticasVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadisticasVentasActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Selecciona una accion de inventario");

        activarProductos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        activarProductos.setText("Activar productos");
        activarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activarProductosActionPerformed(evt);
            }
        });

        desactivarProductos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        desactivarProductos.setText("Desactivar Productos");
        desactivarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desactivarProductosActionPerformed(evt);
            }
        });

        consultarProductos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        consultarProductos.setText("Consultar productos");
        consultarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarProductosActionPerformed(evt);
            }
        });

        pantallaPrincipla.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pantallaPrincipla.setText("Volver pantalla principal");
        pantallaPrincipla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pantallaPrinciplaActionPerformed(evt);
            }
        });

        CerrarAplicacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CerrarAplicacion.setText("Cerrar la aplicacion");
        CerrarAplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarAplicacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cerrarCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iniciarCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estadisticasVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(desactivarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(activarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(consultarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(505, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CerrarAplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pantallaPrincipla, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(activarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(desactivarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(consultarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(iniciarCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cerrarCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(estadisticasVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pantallaPrincipla, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CerrarAplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarCajaActionPerformed
        metodos.iniciarCaja();
    }//GEN-LAST:event_iniciarCajaActionPerformed

    private void cerrarCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarCajaActionPerformed
        metodos.cerrarCaja();
    }//GEN-LAST:event_cerrarCajaActionPerformed

    private void estadisticasVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadisticasVentasActionPerformed
        metodos.consultarEstadisticasVentas();
    }//GEN-LAST:event_estadisticasVentasActionPerformed

    private void consultarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarProductosActionPerformed
        metodos.consultarProductos();
    }//GEN-LAST:event_consultarProductosActionPerformed

    private void activarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activarProductosActionPerformed
        metodos.activarProductos();
    }//GEN-LAST:event_activarProductosActionPerformed

    private void desactivarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desactivarProductosActionPerformed
        metodos.desactivarProductos();
    }//GEN-LAST:event_desactivarProductosActionPerformed

    private void pantallaPrinciplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pantallaPrinciplaActionPerformed
        metodos.volverPantallaPrincipal();
    }//GEN-LAST:event_pantallaPrinciplaActionPerformed

    private void CerrarAplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarAplicacionActionPerformed
        if (new ActividadEmpleados().solicitarPermisos("Introduce el numero de empleado", 2)) {
            System.exit(0);
        }
    }//GEN-LAST:event_CerrarAplicacionActionPerformed

    public JButton getActivarProductos() {
        return activarProductos;
    }

    public JButton getCerrarCaja() {
        return cerrarCaja;
    }

    public JButton getConsultarProductos() {
        return consultarProductos;
    }

    public JButton getDesactivarProductos() {
        return desactivarProductos;
    }

    public JButton getEstadisticasVentas() {
        return estadisticasVentas;
    }

    public JButton getIniciarCaja() {
        return iniciarCaja;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CerrarAplicacion;
    private javax.swing.JButton activarProductos;
    private javax.swing.JButton cerrarCaja;
    private javax.swing.JButton consultarProductos;
    private javax.swing.JButton desactivarProductos;
    private javax.swing.JButton estadisticasVentas;
    private javax.swing.JButton iniciarCaja;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JButton pantallaPrincipla;
    // End of variables declaration//GEN-END:variables
}
