package productos.interfazProducto.casillaVacia;

import auxiliares.utilidadesGraficas.coloresInterfaz.ColoresInterfaz;

/**
 *
 * @author aleja
 */
public class CasillaVacia extends javax.swing.JPanel {

    /**
     * Creates new form CasillaVacia
     */
    public CasillaVacia() {
        initComponents();
        this.setSize(258, 78);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(ColoresInterfaz.SECUNDARIO_CHAMPAGNE);
        setMaximumSize(new java.awt.Dimension(258, 78));
        setMinimumSize(new java.awt.Dimension(258, 78));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
