package productos.interfazPedido.SeleccionProductos.ProductoSeleccionado;

import auxiliares.utilidadesGraficas.coloresInterfaz.ColoresInterfaz;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import productos.modelo.Producto;

/**
 * Metodo que muestra la informacion de un producto en el listado de productos
 * seleccionados
 *
 * @author Alejandro Perellón López
 */
public class PanelProductoSeleccionado extends javax.swing.JPanel {

    private PanelProductoSeleccionadoMetodos metodos = new PanelProductoSeleccionadoMetodos(this);

    private Producto producto;

    /**
     * Creates new form PanelProductoSeleccionado
     */
    public PanelProductoSeleccionado(Producto pro) {
        this.producto = pro;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreProducto = new javax.swing.JLabel();
        precioProducto = new javax.swing.JLabel();
        informacionAdicional = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(0, 0));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        nombreProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreProducto.setText("jLabel1");

        precioProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        precioProducto.setText("12.30 €");

        informacionAdicional.setEditable(false);
        informacionAdicional.setBackground(new java.awt.Color(255, 255, 255));
        informacionAdicional.setColumns(20);
        informacionAdicional.setLineWrap(true);
        informacionAdicional.setRows(5);
        informacionAdicional.setText("holaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholaholahola");
        informacionAdicional.setWrapStyleWord(true);
        informacionAdicional.setBorder(null);
        informacionAdicional.setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nombreProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(precioProducto))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(informacionAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreProducto)
                    .addComponent(precioProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(informacionAdicional)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        this.setBackground(ColoresInterfaz.PRIMARIO_DORADO);
    }//GEN-LAST:event_formFocusGained

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        this.setBackground(Color.WHITE);
    }//GEN-LAST:event_formFocusLost

    public Producto getProducto() {
        return producto;
    }
    public JTextArea getInformacionAdicional() {
        return informacionAdicional;
    }

    public JLabel getNombreProducto() {
        return nombreProducto;
    }

    public JLabel getPrecioProducto() {
        return precioProducto;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea informacionAdicional;
    private javax.swing.JLabel nombreProducto;
    private javax.swing.JLabel precioProducto;
    // End of variables declaration//GEN-END:variables
}
