package interfazGrafica;

import java.math.RoundingMode;
import javax.swing.ImageIcon;

import models.Producto;

/**
 * Esta clase muestra un panel con la informacion de un producto, entre la
 * informacion muestra una imagen, el nombre del producto y el precio del mismo
 *
 * @author Alejandro Perellón López
 */
public class CasillaProducto extends javax.swing.JPanel {

    private final PanelPedido panel;
    private final Producto producto;

    /**
     * Este constructor permite crear un objeto que contiene un jpanel que
     * muestra toda la informacion del producto, para ello primero solicita la
     * informacion del producto y mediante el metood de establecerdatosproducto
     * se insertan los datos en la casilla
     *
     * @param producto es el producto que se va a añadir en el panel de pedido
     * @param panel es el panel que se va a modificar con el nuevo producto
     * añadido
     */
    public CasillaProducto(Producto producto, PanelPedido panel) {
        initComponents();
        //Añadimos el panel de pedido para realizar modificaciones en el 
        this.panel = panel;
        //Anadimos el producto para obtener los datos del producto y para anadirlo al listado en caso de seleccionarse
        this.producto = producto;
        //Establecemos los datos del producto en la casilla
        establecerDatosProducto(producto);
        this.revalidate();
        this.repaint();
    }

    /**
     * Este metodo establece toda la informacion del producto en la casilla, a
     * traves del objeto {@link  Producto} obtiene el nombre, imagen y precio del
     * producto
     *
     * @param pro es el producto del que se va a extraer la informacion
     */
    private void establecerDatosProducto(Producto pro) {
        if (pro.getImagenProducto().exists()) {
            cuadroImagen.setIcon(new ImageIcon(pro.getImagenProducto().getAbsolutePath()));
        }
        textoPrecio.setText("€ " + pro.getPrecioVenta().setScale(2, RoundingMode.HALF_UP));
        textoNombre.setText(pro.getNombreProducto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoPrecio = new javax.swing.JLabel();
        cuadroImagen = new javax.swing.JLabel();
        textoNombre = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        setMaximumSize(new java.awt.Dimension(256, 105));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        textoPrecio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textoPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoPrecio.setText("€ 0,00");

        cuadroImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/productos/InterfazGrafica/imagenError/imageNotFound64.png"))); // NOI18N

        textoNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textoNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoNombre.setText("Sample text");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cuadroImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 129, Short.MAX_VALUE)
                        .addComponent(textoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoPrecio))
                    .addComponent(cuadroImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este metodo se activa cuando se realiza click en cualquier parte del
     * panel, tras la`pulsacion realiza la insercion del producto en el pedido
     * principal de {@link PanelPedido}
     *
     * @param evt el evento de activa cuando se pulsa en cualquier parte del
     * panel
     */
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        new GestionPanelPedido().actualizarListaPedido(producto, panel);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cuadroImagen;
    private javax.swing.JLabel textoNombre;
    private javax.swing.JLabel textoPrecio;
    // End of variables declaration//GEN-END:variables

}
