package interfazGrafica;

import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JPanel;

import models.Producto;
import models.InterfazGrafica.EdicionProductos.PanelEdicionProductos;

/**
 *
 * Este metodo contiene el panel principal en el cual se van a realizar los
 * pedidos, incluye todas las categorias de los productos y las diferentes
 * opciones de personalizacion del pedido y de la orden de productos
 *
 * @author Alejandro Perellón López
 */
public class PanelPedido extends javax.swing.JPanel {

    // Inicializamos el modelo de lista (esto debe hacerse antes de usar jList1)
    private final List<Producto> listaPedido = new ArrayList<>();
    private final DefaultListModel<String> modelo = new DefaultListModel<>();

    public List<Producto> getListaPedido() {
        return listaPedido;
    }

    public DefaultListModel<String> getModelo() {
        return modelo;
    }

    public JList<String> getjList1() {
        return jList1;
    }

    public JButton getBotonEditar() {
        return botonEditar;
    }

    public JPanel getPanelProductos() {
        return panelProductos;
    }

    /**
     * Esta clase permite generar un panel de pedido que contiene todas las
     * categorias principales para realizar un pedido de manera satisfactoriaº
     */
    public PanelPedido() {
        initComponents();
        //Establecemos una disposicion de border
        panelProductos.setLayout(new BorderLayout());

        //Vamos a generar el panel de productos con la categoria principal de hamburguesas
        panelProductos.add(new PanelProductos(this, "Hamburguesa"));

        /**
         * Crear un ListCellRenderer personalizado para cambiar el color de
         * selección y tener dos lineas en los jlist
         */
        GestionJlist.setMultilineListRenderer(jList1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        panelProductos = new javax.swing.JPanel();
        botonHamburguesas = new javax.swing.JButton();
        botonComplementos = new javax.swing.JButton();
        botonBebidas = new javax.swing.JButton();
        botonPostres = new javax.swing.JButton();
        botonSalsas = new javax.swing.JButton();
        botonEnsaladas = new javax.swing.JButton();
        botonOtros = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        botonOtros2 = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonCobrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jList1.setBackground(new java.awt.Color(102, 102, 102));
        jList1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.setModel(modelo);
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout panelProductosLayout = new javax.swing.GroupLayout(panelProductos);
        panelProductos.setLayout(panelProductosLayout);
        panelProductosLayout.setHorizontalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelProductosLayout.setVerticalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );

        botonHamburguesas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonHamburguesas.setText("Hamburguesas");
        botonHamburguesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHamburguesasActionPerformed(evt);
            }
        });

        botonComplementos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonComplementos.setText("Complementos");
        botonComplementos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComplementosActionPerformed(evt);
            }
        });

        botonBebidas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonBebidas.setText("Bebidas");
        botonBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBebidasActionPerformed(evt);
            }
        });

        botonPostres.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonPostres.setText("Postres");
        botonPostres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPostresActionPerformed(evt);
            }
        });

        botonSalsas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonSalsas.setText("Salsas");

        botonEnsaladas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonEnsaladas.setText("Ensaladas");

        botonOtros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonOtros.setText("Otros");

        botonEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonEditar.setText("Editar");
        botonEditar.setEnabled(false);
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        botonOtros2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonOtros2.setText("Otros");

        botonBorrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonBorrar.setText("Borrar");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        botonCobrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonCobrar.setText("Cobrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonHamburguesas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonComplementos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonPostres, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonSalsas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonEnsaladas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonOtros, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonOtros2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonHamburguesas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonComplementos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonPostres, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonSalsas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonEnsaladas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonOtros, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(botonOtros2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Este metodo se encarga de mostrar las hamburguesas disponibles en el menu
     *
     * @param evt el metood se activa cuando se pulsa sobre el boton
     */
    private void botonHamburguesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHamburguesasActionPerformed
        panelProductos.setLayout(new BorderLayout());
        panelProductos.add(new PanelProductos(this, "Hamburguesa"));

    }//GEN-LAST:event_botonHamburguesasActionPerformed
    /**
     * Este metodo se encarga de mostrar los complementos disponibles en el menu
     *
     * @param evt el metood se activa cuando se pulsa sobre el boton
     */
    private void botonComplementosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComplementosActionPerformed
        panelProductos.setLayout(new BorderLayout());
        panelProductos.add(new PanelProductos(this, "Complemento"));
    }//GEN-LAST:event_botonComplementosActionPerformed
    /**
     * Este metodo realiza la eliminacion de el elemento seleccionado en el
     * {@link JList}, para ello selecciona la posicion del elemento, elimina el
     * listado de productos pedidos y del modelo del jlist.
     *
     * Por ultimo selecciona el producto anterior para continuar con el pedido
     *
     * @param evt el evento se activa cuando se pulsa el boton
     */
    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        int posicion = jList1.getSelectedIndex();
        //Establecemos la seleccion en el siguiente elemento al borrado
        jList1.setSelectedIndex(posicion - 1);
        //Borramos del modelo y de la lista de pedido el elemento seleccionado
        modelo.remove(posicion);
        listaPedido.remove(posicion);
    }//GEN-LAST:event_botonBorrarActionPerformed
    /**
     * Si se hace una pulsacion sobre el jlist se va a buscar el objeto
     * seleccionado y se va a comprobar si es posible la edicion del producto
     * para modificar ingredientes o extras
     *
     * @param evt el evento se activa en caso de que se pulse en cualquier lado
     * sobre el jlist
     */
    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        new GestionPanelPedido().comprobarEdicionProductos(this);
    }//GEN-LAST:event_jList1MouseClicked

    private void botonBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBebidasActionPerformed
        panelProductos.setLayout(new BorderLayout());
        panelProductos.add(new PanelProductos(this, "Bebida"));
    }//GEN-LAST:event_botonBebidasActionPerformed

    private void botonPostresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPostresActionPerformed
        panelProductos.setLayout(new BorderLayout());
        panelProductos.add(new PanelProductos(this, "Postres"));
    }//GEN-LAST:event_botonPostresActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        //Vaciamos el panel de productos para ahora mostrar el panel de edicion
        panelProductos.removeAll();
        //Mostramos el panel de la edicion de productos
        panelProductos.add(new PanelEdicionProductos(listaPedido.get(jList1.getSelectedIndex())));
        //Revalidamos y pintamos el objeto
        panelProductos.revalidate();
        panelProductos.repaint();
    }//GEN-LAST:event_botonEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBebidas;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonCobrar;
    private javax.swing.JButton botonComplementos;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEnsaladas;
    private javax.swing.JButton botonHamburguesas;
    private javax.swing.JButton botonOtros;
    private javax.swing.JButton botonOtros2;
    private javax.swing.JButton botonPostres;
    private javax.swing.JButton botonSalsas;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelProductos;
    // End of variables declaration//GEN-END:variables
}
