package interfazGrafica;

import java.util.ArrayList;
import java.util.List;

import models.Producto;

/**
 * Este metodo contiene un panel el cual muestra todos los productos de la
 * categoria seleccionada.
 *
 * Tambien permite la seleccion de los productos mediante filtros.
 *
 * Dentro de este panel se situan todos las {@link CasillaProducto} con la
 * informacion de cada producto, en caso de seleccionarse el producto se añade
 * al pedido principal
 *
 * @author Alejandro Perellón López
 */
public class PanelProductos extends javax.swing.JPanel {

    // Listado completo de todas los productos
    private List<Producto> listaProductosCompleta = new ArrayList<>();
    // Listado de productos bajo condiciones como las categorias
    private List<Producto> listaProductos;
    // Panel de pedido que se utilizara para realizar modificaciones de los pedidos hechos
    private final PanelPedido panelPedido;

    /**
     * Este clase contiene el panelPedido que permite la seleccion de los
     * productos, segun el nombre introducido va a mostrar y trabajar con unos
     * productos u otros
     *
     * @param panelPedido es el {@link PanelPedido} principal que permite
     * realizar el pedido, se introduce con el objetivo de realizar
     * modificaciones en el panel para añadir o actualizar elementos en la orden
     * de pedido
     * @param nombreProducto es el nombre de la categoria de los productos
     */
    public PanelProductos(PanelPedido panelPedido, String nombreProducto) {
        initComponents();

        // Panel de pedido que se utilizara para realizar modificaciones de los pedidos hechos
        this.panelPedido = panelPedido;

        //Actualizamos el listado completo de todos los productos
        listaProductosCompleta = new GestionProductos().consultaListadoProductosBBDD(nombreProducto);

        /**
         * Añadimos la lista de productos con todas los productos, esto se usara
         * para navegar entre el tipo de producto entre las categorias
         * introducidas
         *
         * En el primer paso vamos a mostrar todos los productos sin filtro
         */
        listaProductos = listaProductosCompleta;
        //Mostramos todos los productos en el panelPedido principal 
        new GestionPanelProductos().mostrarProductosPanel(panelListadoProductos, listaProductos, panelPedido);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonVerTodo = new javax.swing.JButton();
        botonCarne = new javax.swing.JButton();
        botonPollo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelListadoProductos = new javax.swing.JPanel();

        botonVerTodo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonVerTodo.setText("Ver todo");
        botonVerTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerTodoActionPerformed(evt);
            }
        });

        botonCarne.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonCarne.setText("Carne");
        botonCarne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarneActionPerformed(evt);
            }
        });

        botonPollo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonPollo.setText("Pollo");
        botonPollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPolloActionPerformed(evt);
            }
        });

        panelListadoProductos.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panelListadoProductosLayout = new javax.swing.GroupLayout(panelListadoProductos);
        panelListadoProductos.setLayout(panelListadoProductosLayout);
        panelListadoProductosLayout.setHorizontalGroup(
            panelListadoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1258, Short.MAX_VALUE)
        );
        panelListadoProductosLayout.setVerticalGroup(
            panelListadoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelListadoProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(botonCarne, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonPollo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonVerTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonVerTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonCarne, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonPollo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(431, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Este metodo muestra todos los productos en el panel principal
     */
    private void botonVerTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerTodoActionPerformed
        //Añadimos la lista de hamburguesas con todas las hamburguesas
        //listaProductos = listaProductosCompleta;
        //Establecemos todos los productos en el panel principal
        new GestionPanelProductos().mostrarProductosPanel(panelListadoProductos, listaProductosCompleta, panelPedido);
    }//GEN-LAST:event_botonVerTodoActionPerformed
    /**
     * Este metodo muestra todos los productos en el panel principal que
     * contienen la categoria carne
     */
    private void botonCarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarneActionPerformed
        //Añadimos la lista de hamburguesas con todas las hamburguesas que sean de la categoria carne
        listaProductos = new GestionProductos().listarProductosPorCategoria(listaProductosCompleta, "Carne");
        System.out.println(listaProductos);
        //Establecemos todos los productos en el panel principal
         new GestionPanelProductos().mostrarProductosPanel(panelListadoProductos, listaProductos, panelPedido);
    }//GEN-LAST:event_botonCarneActionPerformed
    /**
     * Este metodo muestra todos los productos en el panel principal que
     * contienen la categoria pollo
     */
    private void botonPolloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPolloActionPerformed
        //Añadimos la lista de hamburguesas con todas las hamburguesas
        listaProductos = new GestionProductos().listarProductosPorCategoria(listaProductosCompleta, "Pollo");
        //Establecemos todos los productos en el panel principal
        new GestionPanelProductos().mostrarProductosPanel(panelListadoProductos, listaProductos, panelPedido);
    }//GEN-LAST:event_botonPolloActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCarne;
    private javax.swing.JButton botonPollo;
    private javax.swing.JButton botonVerTodo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelListadoProductos;
    // End of variables declaration//GEN-END:variables
}
