package productos.interfazPedido.personalizarPedido.edicionProducto;

import javax.swing.JLabel;
import javax.swing.JPanel;
import productos.modelo.Producto;

/**
 * Clase de interfaz grafica que contiene el panel principal que muestra todos
 * los ingredientes y extras del producto
 *
 * @author Alejandro Perellón López
 */
public class PanelEdicionProductos extends javax.swing.JPanel {

    private Producto producto;

    private PanelEdicionProductosMetodos metodos = new PanelEdicionProductosMetodos(this);

    /**
     * Creates new form PanelEdicionProductos
     */
    public PanelEdicionProductos(Producto producto) {
        this.producto = producto;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImagenProducto = new javax.swing.JPanel();
        imagenProducto = new javax.swing.JLabel();
        nombreProducto = new javax.swing.JLabel();
        scrollPanelIngredientesExtras = new javax.swing.JScrollPane();
        panelIngredientesExtras = new javax.swing.JPanel();

        setBackground(new java.awt.Color(88, 214, 141));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setMaximumSize(new java.awt.Dimension(724, 461));

        panelImagenProducto.setBackground(new java.awt.Color(255, 255, 255));

        imagenProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficaErrorProducto/imageNotFound256.png"))); // NOI18N

        nombreProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nombreProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreProducto.setText("Nombre del producto");

        javax.swing.GroupLayout panelImagenProductoLayout = new javax.swing.GroupLayout(panelImagenProducto);
        panelImagenProducto.setLayout(panelImagenProductoLayout);
        panelImagenProductoLayout.setHorizontalGroup(
            panelImagenProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImagenProductoLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(panelImagenProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(nombreProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imagenProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        panelImagenProductoLayout.setVerticalGroup(
            panelImagenProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImagenProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagenProducto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scrollPanelIngredientesExtras.setBorder(null);
        scrollPanelIngredientesExtras.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        javax.swing.GroupLayout panelIngredientesExtrasLayout = new javax.swing.GroupLayout(panelIngredientesExtras);
        panelIngredientesExtras.setLayout(panelIngredientesExtrasLayout);
        panelIngredientesExtrasLayout.setHorizontalGroup(
            panelIngredientesExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 997, Short.MAX_VALUE)
        );
        panelIngredientesExtrasLayout.setVerticalGroup(
            panelIngredientesExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );

        scrollPanelIngredientesExtras.setViewportView(panelIngredientesExtras);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelImagenProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanelIngredientesExtras, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImagenProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollPanelIngredientesExtras, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public Producto getProducto() {
        return producto;
    }

    public JLabel getImagenProducto() {
        return imagenProducto;
    }

    public JLabel getNombreProducto() {
        return nombreProducto;
    }

    public JPanel getPanelImagenProducto() {
        return panelImagenProducto;
    }

    public JPanel getPanelIngredientesExtras() {
        return panelIngredientesExtras;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagenProducto;
    private javax.swing.JLabel nombreProducto;
    private javax.swing.JPanel panelImagenProducto;
    private javax.swing.JPanel panelIngredientesExtras;
    private javax.swing.JScrollPane scrollPanelIngredientesExtras;
    // End of variables declaration//GEN-END:variables

}
