package pedido.interfazPedido;

import javax.swing.DefaultListModel;
import javax.swing.JPanel;
import pedido.modelo.Pedido;

/**
 * Clase que maneja de manera grafica la creacion de un pedido
 *
 * @author Alejandro Perellón López
 */
public class PanelPedido extends javax.swing.JPanel {

    private PanelPedidoMetodos metodos = new PanelPedidoMetodos(this);

    private DefaultListModel<Object> modeloLista = new DefaultListModel<>();

    private Pedido pedido;

    /**
     * Creates new form PanelPedido
     */
    public PanelPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSeleccionTipoProducto = new javax.swing.JPanel();
        Hamburguesas = new javax.swing.JButton();
        bebidas = new javax.swing.JButton();
        Complementos = new javax.swing.JButton();
        Postres = new javax.swing.JButton();
        categoria5 = new javax.swing.JButton();
        panelAjustesPedido = new javax.swing.JPanel();
        cobrar = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelProductos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaProductosPedidos = new javax.swing.JList<>();

        setBackground(new java.awt.Color(255, 51, 102));
        setPreferredSize(new java.awt.Dimension(1366, 716));

        Hamburguesas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Hamburguesas.setText("Hamburguesas");
        Hamburguesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HamburguesasActionPerformed(evt);
            }
        });

        bebidas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bebidas.setText("Bebidas");
        bebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bebidasActionPerformed(evt);
            }
        });

        Complementos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Complementos.setText("Complementos");
        Complementos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComplementosActionPerformed(evt);
            }
        });

        Postres.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Postres.setText("Postres");
        Postres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostresActionPerformed(evt);
            }
        });

        categoria5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        categoria5.setText("Categoria 5");
        categoria5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoria5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSeleccionTipoProductoLayout = new javax.swing.GroupLayout(panelSeleccionTipoProducto);
        panelSeleccionTipoProducto.setLayout(panelSeleccionTipoProductoLayout);
        panelSeleccionTipoProductoLayout.setHorizontalGroup(
            panelSeleccionTipoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeleccionTipoProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Hamburguesas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Complementos, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Postres, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(categoria5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSeleccionTipoProductoLayout.setVerticalGroup(
            panelSeleccionTipoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeleccionTipoProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSeleccionTipoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hamburguesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Complementos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bebidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Postres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(categoria5))
                .addContainerGap())
        );

        panelAjustesPedido.setPreferredSize(new java.awt.Dimension(200, 666));

        cobrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cobrar.setText("Cobrar");

        Editar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Editar.setText("Editar");

        javax.swing.GroupLayout panelAjustesPedidoLayout = new javax.swing.GroupLayout(panelAjustesPedido);
        panelAjustesPedido.setLayout(panelAjustesPedidoLayout);
        panelAjustesPedidoLayout.setHorizontalGroup(
            panelAjustesPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAjustesPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAjustesPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelAjustesPedidoLayout.setVerticalGroup(
            panelAjustesPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAjustesPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cobrar)
                .addContainerGap())
        );

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(898, 640));

        javax.swing.GroupLayout panelProductosLayout = new javax.swing.GroupLayout(panelProductos);
        panelProductos.setLayout(panelProductosLayout);
        panelProductosLayout.setHorizontalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 915, Short.MAX_VALUE)
        );
        panelProductosLayout.setVerticalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelProductos);

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setPreferredSize(new java.awt.Dimension(250, 700));

        listaProductosPedidos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listaProductosPedidos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelAjustesPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelSeleccionTipoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelSeleccionTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelAjustesPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE))))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void HamburguesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HamburguesasActionPerformed
        metodos.mostrarHamburguesas();
    }//GEN-LAST:event_HamburguesasActionPerformed

    private void ComplementosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComplementosActionPerformed
        metodos.mostrarComplementos();
    }//GEN-LAST:event_ComplementosActionPerformed

    private void bebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bebidasActionPerformed
        metodos.mostrarBebidas();
    }//GEN-LAST:event_bebidasActionPerformed

    private void PostresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostresActionPerformed
        metodos.mostrarPostres();
    }//GEN-LAST:event_PostresActionPerformed

    private void categoria5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoria5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoria5ActionPerformed

    public DefaultListModel<Object> getModeloLista() {
        return modeloLista;
    }

    

    public JPanel getPanelProductos() {
        return panelProductos;
    }

    public Pedido getPedido() {
        return pedido;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Complementos;
    private javax.swing.JButton Editar;
    private javax.swing.JButton Hamburguesas;
    private javax.swing.JButton Postres;
    private javax.swing.JButton bebidas;
    private javax.swing.JButton categoria5;
    private javax.swing.JButton cobrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listaProductosPedidos;
    private javax.swing.JPanel panelAjustesPedido;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JPanel panelSeleccionTipoProducto;
    // End of variables declaration//GEN-END:variables
}
