package pedido.interfazPedido.filtros;

import auxiliares.singleton.ClasesEstaticas;
import auxiliares.solicitarDatos.tecladoPantalla.TecladoEnPantalla;
import auxiliares.solicitarDatos.tecladoPantalla.TecladoEnPantallaMetodos;
import auxiliares.utilidadesGraficas.coloresInterfaz.ColoresInterfaz;
import java.awt.Dimension;
import javax.swing.JTextArea;
import pedido.interfazPedido.PanelPedidoMetodos;

/**
 *
 * @author Alejandro Perellón López
 */
public class FiltroTodosLosProductos extends javax.swing.JPanel {

    /**
     * Creates new form FiltroHamburguesa
     */
    public FiltroTodosLosProductos() {
        initComponents();
        this.setPreferredSize(new Dimension(159, 437));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFiltros = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textoBuscado = new javax.swing.JTextArea();
        botonBuscar = new javax.swing.JButton();

        setBackground(ColoresInterfaz.SECUNDARIO_CHAMPAGNE);

        panelFiltros.setBackground(ColoresInterfaz.SECUNDARIO_CHAMPAGNE);

        jLabel1.setBackground(ColoresInterfaz.SECUNDARIO_CHAMPAGNE);
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficaPersonalizarProducto/filtrar.png"))); // NOI18N
        jLabel1.setText("FILTROS");

        textoBuscado.setEditable(false);
        textoBuscado.setBackground(new java.awt.Color(255, 255, 255));
        textoBuscado.setColumns(20);
        textoBuscado.setLineWrap(true);
        textoBuscado.setRows(5);
        textoBuscado.setText("Busqueda...");
        textoBuscado.setWrapStyleWord(true);

        botonBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonBuscar.setText("Buscar producto");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFiltrosLayout = new javax.swing.GroupLayout(panelFiltros);
        panelFiltros.setLayout(panelFiltrosLayout);
        panelFiltrosLayout.setHorizontalGroup(
            panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(textoBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelFiltrosLayout.setVerticalGroup(
            panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltrosLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 326, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        textoBuscado.setText(new TecladoEnPantallaMetodos(new TecladoEnPantalla()).iniciarTecladoPantalla());
        new PanelPedidoMetodos(ClasesEstaticas.getPanelPedido()).mostrarTodasCasillas(this);
    }//GEN-LAST:event_botonBuscarActionPerformed

    public JTextArea getTextoBuscado() {
        return textoBuscado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelFiltros;
    private javax.swing.JTextArea textoBuscado;
    // End of variables declaration//GEN-END:variables
}
