package pedido.interfazPedido.filtros;

import auxiliares.singleton.ClasesEstaticas;
import auxiliares.utilidadesGraficas.coloresInterfaz.ColoresInterfaz;
import java.awt.Panel;
import javax.swing.ButtonGroup;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import pedido.interfazPedido.PanelPedidoMetodos;

/**
 *
 * @author Alejandro Perellón López
 */
public class FiltroHamburguesa extends javax.swing.JPanel {

    /**
     * Creates new form FiltroHamburguesa
     */
    public FiltroHamburguesa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoProducto = new javax.swing.ButtonGroup();
        opcionMenu = new javax.swing.ButtonGroup();
        panelFiltros = new javax.swing.JPanel();
        textoFiltro = new javax.swing.JLabel();
        todosLosProductos = new javax.swing.JRadioButton();
        soloVacuno = new javax.swing.JRadioButton();
        soloPollo = new javax.swing.JRadioButton();
        textoTipoCarne = new javax.swing.JLabel();
        textoOpcionMenu = new javax.swing.JLabel();
        soloConMenu = new javax.swing.JRadioButton();
        soloSinMenu = new javax.swing.JRadioButton();
        todosLosProductos1 = new javax.swing.JRadioButton();

        setBackground(ColoresInterfaz.SECUNDARIO_CHAMPAGNE);

        panelFiltros.setBackground(ColoresInterfaz.SECUNDARIO_CHAMPAGNE);

        textoFiltro.setBackground(ColoresInterfaz.SECUNDARIO_CHAMPAGNE);
        textoFiltro.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        textoFiltro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoFiltro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficaPersonalizarProducto/filtrar.png"))); // NOI18N
        textoFiltro.setText("FILTROS");

        tipoProducto.add(todosLosProductos);
        todosLosProductos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        todosLosProductos.setSelected(true);
        todosLosProductos.setText("Todas");
        todosLosProductos.setActionCommand("Todos");
        todosLosProductos.setContentAreaFilled(false);
        todosLosProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soloActionPerformed(evt);
            }
        });

        tipoProducto.add(soloVacuno);
        soloVacuno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        soloVacuno.setText("Vacuno");
        soloVacuno.setActionCommand("vacuno");
        soloVacuno.setContentAreaFilled(false);
        soloVacuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soloActionPerformed(evt);
            }
        });

        tipoProducto.add(soloPollo);
        soloPollo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        soloPollo.setText("Pollo");
        soloPollo.setActionCommand("pollo");
        soloPollo.setContentAreaFilled(false);
        soloPollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soloActionPerformed(evt);
            }
        });

        textoTipoCarne.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoTipoCarne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoTipoCarne.setText("Tipo carne");

        textoOpcionMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoOpcionMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoOpcionMenu.setText("Opcion menú");

        opcionMenu.add(soloConMenu);
        soloConMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        soloConMenu.setText("Con menú");
        soloConMenu.setActionCommand("true");
        soloConMenu.setContentAreaFilled(false);
        soloConMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soloActionPerformed(evt);
            }
        });

        opcionMenu.add(soloSinMenu);
        soloSinMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        soloSinMenu.setText("Sin menú");
        soloSinMenu.setActionCommand("false");
        soloSinMenu.setContentAreaFilled(false);
        soloSinMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soloActionPerformed(evt);
            }
        });

        opcionMenu.add(todosLosProductos1);
        todosLosProductos1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        todosLosProductos1.setSelected(true);
        todosLosProductos1.setText("Todas");
        todosLosProductos1.setActionCommand("Todos");
        todosLosProductos1.setContentAreaFilled(false);
        todosLosProductos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFiltrosLayout = new javax.swing.GroupLayout(panelFiltros);
        panelFiltros.setLayout(panelFiltrosLayout);
        panelFiltrosLayout.setHorizontalGroup(
            panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoTipoCarne, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(todosLosProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(soloVacuno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(soloPollo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoOpcionMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(todosLosProductos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(soloConMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(soloSinMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelFiltrosLayout.setVerticalGroup(
            panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltrosLayout.createSequentialGroup()
                .addComponent(textoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoTipoCarne, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(todosLosProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soloVacuno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soloPollo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoOpcionMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(todosLosProductos1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soloConMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soloSinMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void soloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soloActionPerformed
       new PanelPedidoMetodos(ClasesEstaticas.getPanelPedido()).mostraCasillasHamburguesas(this);
    }//GEN-LAST:event_soloActionPerformed

    public ButtonGroup getOpcionMenu() {
        return opcionMenu;
    }

    public ButtonGroup getTipoProducto() {
        return tipoProducto;
    }

    public JPanel getPanelFiltros() {
        return panelFiltros;
    }

    public JRadioButton getSoloConMenu() {
        return soloConMenu;
    }

    public JRadioButton getSoloPollo() {
        return soloPollo;
    }

    public JRadioButton getSoloSinMenu() {
        return soloSinMenu;
    }

    public JRadioButton getSoloVacuno() {
        return soloVacuno;
    }

    public JRadioButton getTodosLosProductos() {
        return todosLosProductos;
    }

    public JRadioButton getTodosLosProductos1() {
        return todosLosProductos1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup opcionMenu;
    private javax.swing.JPanel panelFiltros;
    private javax.swing.JRadioButton soloConMenu;
    private javax.swing.JRadioButton soloPollo;
    private javax.swing.JRadioButton soloSinMenu;
    private javax.swing.JRadioButton soloVacuno;
    private javax.swing.JLabel textoFiltro;
    private javax.swing.JLabel textoOpcionMenu;
    private javax.swing.JLabel textoTipoCarne;
    private javax.swing.ButtonGroup tipoProducto;
    private javax.swing.JRadioButton todosLosProductos;
    private javax.swing.JRadioButton todosLosProductos1;
    // End of variables declaration//GEN-END:variables
}
