package pedido.interfazPedido.filtros;

import auxiliares.singleton.ClasesEstaticas;
import auxiliares.utilidadesGraficas.coloresInterfaz.ColoresInterfaz;
import java.awt.Dimension;
import javax.swing.ButtonGroup;
import pedido.interfazPedido.PanelPedidoMetodos;

/**
 *
 * @author Alejandro Perellón López
 */
public class FiltroPostre extends javax.swing.JPanel {

    /**
     * Creates new form FiltroHamburguesa
     */
    public FiltroPostre() {
        initComponents();
        this.setPreferredSize(new Dimension(159, 437));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTopping = new javax.swing.ButtonGroup();
        grupoTipoHelado = new javax.swing.ButtonGroup();
        panelFiltros = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textoTipoTopping = new javax.swing.JLabel();
        soloChocolate = new javax.swing.JRadioButton();
        soloChocolateBlanco = new javax.swing.JRadioButton();
        todosLosProductos = new javax.swing.JRadioButton();
        soloCaramelo = new javax.swing.JRadioButton();
        textoTipoHelado = new javax.swing.JLabel();
        soloFrostie = new javax.swing.JRadioButton();
        soloMiniFrostie = new javax.swing.JRadioButton();
        todosLosProductos1 = new javax.swing.JRadioButton();

        setBackground(ColoresInterfaz.SECUNDARIO_CHAMPAGNE);

        panelFiltros.setBackground(ColoresInterfaz.SECUNDARIO_CHAMPAGNE);

        jLabel1.setBackground(ColoresInterfaz.SECUNDARIO_CHAMPAGNE);
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficaPersonalizarProducto/filtrar.png"))); // NOI18N
        jLabel1.setText(ClasesEstaticas.getProveedorMensaje().findMessage("FILTROS_TITULO"));

        textoTipoTopping.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoTipoTopping.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoTipoTopping.setText(ClasesEstaticas.getProveedorMensaje().findMessage("FILTROS_POSTRES_TOPPING"));

        grupoTopping.add(soloChocolate);
        soloChocolate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        soloChocolate.setText(ClasesEstaticas.getProveedorMensaje().findMessage("FILTROS_POSTRES_CHOCOLATE"));
        soloChocolate.setActionCommand("Choco");
        soloChocolate.setContentAreaFilled(false);
        soloChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });

        grupoTopping.add(soloChocolateBlanco);
        soloChocolateBlanco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        soloChocolateBlanco.setText(ClasesEstaticas.getProveedorMensaje().findMessage("FILTROS_POSTRES_CHOCOLATE_BLANCO"));
        soloChocolateBlanco.setActionCommand("Blanco");
        soloChocolateBlanco.setContentAreaFilled(false);
        soloChocolateBlanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });

        grupoTopping.add(todosLosProductos);
        todosLosProductos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        todosLosProductos.setSelected(true);
        todosLosProductos.setText(ClasesEstaticas.getProveedorMensaje().findMessage("FILTROS_POSTRES_TODOS"));
        todosLosProductos.setActionCommand("todos");
        todosLosProductos.setContentAreaFilled(false);
        todosLosProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });

        grupoTopping.add(soloCaramelo);
        soloCaramelo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        soloCaramelo.setText(ClasesEstaticas.getProveedorMensaje().findMessage("FILTROS_POSTRES_CARAMELO"));
        soloCaramelo.setActionCommand("Caramelo");
        soloCaramelo.setContentAreaFilled(false);
        soloCaramelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });

        textoTipoHelado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoTipoHelado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoTipoHelado.setText(ClasesEstaticas.getProveedorMensaje().findMessage("FILTROS_POSTRES_TIPO_HELADO"));

        grupoTipoHelado.add(soloFrostie);
        soloFrostie.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        soloFrostie.setText(ClasesEstaticas.getProveedorMensaje().findMessage("FILTROS_POSTRES_TIPO_HELADO_FROSTIE"));
        soloFrostie.setContentAreaFilled(false);
        soloFrostie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });

        grupoTipoHelado.add(soloMiniFrostie);
        soloMiniFrostie.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        soloMiniFrostie.setText(ClasesEstaticas.getProveedorMensaje().findMessage("FILTROS_POSTRES_TIPO_HELADO_MINI_FROSTIE"));
        soloMiniFrostie.setActionCommand("Mini");
        soloMiniFrostie.setContentAreaFilled(false);
        soloMiniFrostie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });

        grupoTipoHelado.add(todosLosProductos1);
        todosLosProductos1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        todosLosProductos1.setSelected(true);
        todosLosProductos1.setText(ClasesEstaticas.getProveedorMensaje().findMessage("FILTROS_POSTRES_TIPO_HELADO_TODOS"));
        todosLosProductos1.setActionCommand("todos");
        todosLosProductos1.setContentAreaFilled(false);
        todosLosProductos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });

        javax.swing.GroupLayout panelFiltrosLayout = new javax.swing.GroupLayout(panelFiltros);
        panelFiltros.setLayout(panelFiltrosLayout);
        panelFiltrosLayout.setHorizontalGroup(
            panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
            .addGroup(panelFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoTipoTopping, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(todosLosProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(soloChocolate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(soloChocolateBlanco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(soloCaramelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoTipoHelado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(todosLosProductos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(soloFrostie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(soloMiniFrostie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelFiltrosLayout.setVerticalGroup(
            panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltrosLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoTipoTopping, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(todosLosProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soloChocolate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soloChocolateBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soloCaramelo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoTipoHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(todosLosProductos1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soloFrostie, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soloMiniFrostie, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void accion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accion
        new PanelPedidoMetodos(ClasesEstaticas.getPanelPedido()).mostrarCasillasPostres(this);
    }//GEN-LAST:event_accion

    public ButtonGroup getGrupoTipoHelado() {
        return grupoTipoHelado;
    }

    public ButtonGroup getGrupoTopping() {
        return grupoTopping;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoTipoHelado;
    private javax.swing.ButtonGroup grupoTopping;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelFiltros;
    private javax.swing.JRadioButton soloCaramelo;
    private javax.swing.JRadioButton soloChocolate;
    private javax.swing.JRadioButton soloChocolateBlanco;
    private javax.swing.JRadioButton soloFrostie;
    private javax.swing.JRadioButton soloMiniFrostie;
    private javax.swing.JLabel textoTipoHelado;
    private javax.swing.JLabel textoTipoTopping;
    private javax.swing.JRadioButton todosLosProductos;
    private javax.swing.JRadioButton todosLosProductos1;
    // End of variables declaration//GEN-END:variables
}
